Eugene Hryb Home Work from 16. 11 Flex-Box
viktor-beet-root/beet-root pull request #101
Opened 2020-11-18 12:52 UTC by EugeneHryb

2020-11-20 12:01 UTC, viktor-beet-root requested changes

2020-11-20 12:01 UTC, viktor-beet-root commented on students/EugeneHryb/14_11_KlassWork/css/newletter.css
> +    color: ;
что-то тут пошло не так)

2020-11-20 12:01 UTC, viktor-beet-root commented on students/EugeneHryb/16_11_HomeWork/08_hv_1/css/style.css
> +    src: url(../font/miso-light.otf);
или найди woff2 и woff или конвертируй
отф подключать не правильно

2020-11-20 12:01 UTC, viktor-beet-root commented on students/EugeneHryb/16_11_HomeWork/08_hv_2/08_hv_2.html
> +            <div class="wrapper">
есть два класса враппер это не хорошо
нет семантики

2020-11-20 12:01 UTC, viktor-beet-root commented on students/EugeneHryb/16_11_HomeWork/08_hv_2/08_hv_2.html
> +                    <div class="wrapper_img"><img src="img/img_title_1.jpg" alt="concept car"></div>
HTML у всех статей должен быть одинаков

2020-11-20 12:01 UTC, viktor-beet-root commented on students/EugeneHryb/16_11_HomeWork/08_hv_2/css/style.css
> +    font-family: 'HansKendrick';
нет форбека

2020-11-20 12:01 UTC, viktor-beet-root commented on students/EugeneHryb/16_11_HomeWork/08_hv_2/css/style.css
> +	background: transparent;
что-то с форматированием

2020-11-20 12:01 UTC, viktor-beet-root commented on students/EugeneHryb/16_11_HomeWork/08_hv_2/css/style.css
> +    background-image:linear-gradient( 0deg,black, white );
зачем? этого градиента не будет видно

2020-11-21 09:59 UTC, EugeneHryb commented on students/EugeneHryb/16_11_HomeWork/08_hv_2/css/style.css
> +    background-image:linear-gradient( 0deg,black, white );
Виноват. Нельзя по ночам работать, где то прогавил. Это я баловался пытался понять как работает градиент.

2020-11-21 10:40 UTC, merged