HW Box Model - part 2 (weather forecast)
viktor-beet-root/beet-root pull request #102
Opened 2020-11-19 00:34 UTC by SemenKluchko

2020-11-20 12:03 UTC, viktor-beet-root requested changes

2020-11-20 12:03 UTC, viktor-beet-root commented on students/SemenKluchko/hw8-box-model-2/style.css
> +         url(font/LucidaGrande.ttf);
я уже говорил про шрифты какие два должны быть подключены

2020-11-20 12:03 UTC, viktor-beet-root commented on students/SemenKluchko/index.html
> +</html>
что-то забыл

2020-11-20 23:11 UTC, SemenKluchko commented on students/SemenKluchko/hw8-box-model-2/style.css
> +         url(font/LucidaGrande.ttf);
формат не тот имеется ввиду?

2020-11-21 10:21 UTC, viktor-beet-root requested changes

2020-11-21 10:21 UTC, viktor-beet-root commented on students/SemenKluchko/hw8-box-model-2/style.css
> +         url(font/LucidaGrande.ttf);
да не тот формат

2020-11-22 17:48 UTC, viktor-beet-root requested changes

2020-11-22 17:48 UTC, viktor-beet-root commented on students/SemenKluchko/index.html
> +</html>
заколдованный файл))

2020-11-22 23:07 UTC, merged