HW9 FlexBox Part 1 (coffee)
viktor-beet-root/beet-root pull request #107
Opened 2020-11-19 23:25 UTC by SemenKluchko

2020-11-20 12:25 UTC, viktor-beet-root requested changes

2020-11-20 12:25 UTC, viktor-beet-root commented on students/SemenKluchko/hw9-flexbox-1/index.html
> +                    <img src="images/bean.png" alt="bean inside cup image" title="bean" class="bean">
тут должна быть одна картинка))

2020-11-20 12:25 UTC, viktor-beet-root commented on students/SemenKluchko/hw9-flexbox-1/style.css
> +    src: url(fonts/miso-bold.ttf);
формат не тот

2020-11-20 12:25 UTC, viktor-beet-root commented on students/SemenKluchko/index.html
> +</html>
что-то пошло не так

2020-11-20 23:02 UTC, SemenKluchko commented on students/SemenKluchko/index.html
> +</html>
не знаю, у меня в файле все четко, есть последняя линия
валидатором тоже все ок, я еще раз проверил и вроде все четко

2020-11-21 10:26 UTC, viktor-beet-root requested changes

2020-11-21 10:26 UTC, viktor-beet-root commented on students/SemenKluchko/hw9-flexbox-1/style.css
> +         url(fonts/miso-bold.woff2);
там еще формат шрифта нужно указать
и неправильный порядок

2020-11-21 10:26 UTC, viktor-beet-root commented on students/SemenKluchko/hw9-flexbox-1/style.css
> +    font-family: 'Miso', 'MisoBold', sans-serif;
MisoBold что за)) 
ты подключил мисто и тут прописываешь его главным для бади
а вот MisoBold ты не подключал, и да же если бы подключал, то подумай сам если не прогрузится нормальный шрифт, то что все жирным должно стать))

2020-11-21 10:26 UTC, viktor-beet-root commented on students/SemenKluchko/index.html
> +</html>
ну гит не врет, а показывает что нет старики 
может не на той ветке смотришь
или уже поменял и не запушил

2020-11-22 23:08 UTC, merged