9 homtwork flexbox fantastic design
viktor-beet-root/beet-root pull request #108
Opened 2020-11-20 20:45 UTC by dmytrocherepakhin

2020-11-21 10:10 UTC, viktor-beet-root requested changes
по макету у первой новости на картинке есть линейный градиент снизу вверх, а в стилях я его не наблюдаю

2020-11-21 10:10 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/9_homtwork_FlexBox_Fantastic_design/css/style.css
> +    url('../fonts/Raleway-Regular.woff')format('woff');
перед формат пробел

2020-11-21 11:58 UTC, dmytrocherepakhin commented
градиент сделал, только теперь текст под ним остался и какртинка с сайта не сохраняется (

2020-11-21 17:45 UTC, viktor-beet-root requested changes

2020-11-21 17:45 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/9_homtwork_FlexBox_Fantastic_design/.vscode/settings.json
> +{
этого файла как и папки, не должно быть на сервере удали его из комита
и добавь в свои исключения

2020-11-21 22:35 UTC, viktor-beet-root requested changes
students/cherepakhin_dmytro/index.html
конфликт реши в этом фале уже что-то пошло в мастер

2020-11-22 10:16 UTC, viktor-beet-root requested changes

2020-11-22 10:16 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/9_homtwork_FlexBox_Coffee/css/style.css
> +        url('../fonts/Miso.woff')format("woff");
пробел перед формат

2020-11-22 10:16 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/9_homtwork_FlexBox_Coffee/css/style.css
> +    font-family: 'Lato';;
лишняя ;

2020-11-22 10:30 UTC, viktor-beet-root requested changes

2020-11-22 10:30 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/9_homtwork_FlexBox_Coffee/.vscode/settings.json
> +}
опять))) не правильно в исключения добавил
там в .git есть директория и файл я показывал там нужно правильно указать исключение для папки .vscode так чтобы она не попадала в гит не зависимо от того где лежит

2020-11-22 10:37 UTC, dmytrocherepakhin commented on students/cherepakhin_dmytro/9_homtwork_FlexBox_Coffee/.vscode/settings.json
> +}
исправил, но это было из принятой домашки, которая появилась в этой ветке после ребейса. Теперь опять конфликт.

2020-11-22 10:43 UTC, dmytrocherepakhin commented
исправил, но это было из принятой домашки, которая появилась в этой ветке после ребейса. Теперь опять конфликт.

2020-11-22 11:09 UTC, viktor-beet-root requested changes
students/cherepakhin_dmytro/9_homtwork_FlexBox_Coffee/css/style.css
конфликт с что-то делал ранее что уже в мастере

2020-11-22 11:09 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/9_homtwork_FlexBox_Coffee/css/style.css
> +    src: url('../fonts/Miso-Bold.woff2')format("woff2"),
ну походу пробелы нужно везде поставить))
проверь все подлючения

2020-11-22 11:09 UTC, viktor-beet-root commented on .gitignore
> +.vscode/
а это вызывает конфликт
лучше сделай то что я писал ранее

2020-11-22 12:50 UTC, viktor-beet-root requested changes
Conflicting files
.gitignore
students/cherepakhin_dmytro/9_homtwork_FlexBox_Coffee/css/style.css

2020-11-22 17:11 UTC, merged