HW 10 position
viktor-beet-root/beet-root pull request #122
Opened 2020-11-23 15:58 UTC by SemenKluchko

Вопрос который меня мучает, это как правильно делать бэкграунд картинкой.
Методом :before :after , просто сделать background-image, или положить картинку <img> и задать ей ширину на весь блок?

2020-11-23 16:16 UTC, viktor-beet-root requested changes

2020-11-23 16:16 UTC, viktor-beet-root commented on students/SemenKluchko/hw10-position/style.css
> +    padding-bottom: 120px;
лучше использовать свойство padding и сразу на все стороны прописывать

2020-11-23 16:16 UTC, viktor-beet-root commented on students/SemenKluchko/hw10-position/style.css
> +    min-height: 60px;
это явно декоративный элемент и не думаю что он будет меняться в размерах

2020-11-23 16:16 UTC, viktor-beet-root commented on students/SemenKluchko/hw10-position/style.css
> +    transform: translateX(15px);
это лишнее в данном контексте, просто от левого края поставить и все

2020-11-23 16:16 UTC, viktor-beet-root commented on students/SemenKluchko/hw8_boxmodel/index.html
> +        <section class="container_main">
секшен использован не верно

2020-11-29 21:05 UTC, SemenKluchko commented on students/SemenKluchko/hw8_boxmodel/index.html
> +        <section class="container_main">
это домашка которую ты принял уже, она просто подтянулась вместе с этой веткой
остальное пофиксил

2020-11-30 09:16 UTC, viktor-beet-root requested changes

2020-11-30 09:16 UTC, viktor-beet-root commented on students/SemenKluchko/hw10-position/index.html
> +                    <h2>20</h2><span>nov</span>
20 это аж никак не заголовок

2020-11-30 09:16 UTC, viktor-beet-root commented on students/SemenKluchko/hw10-position/index.html
> +                </div>
этот див должен был быть внутри дива с картинкой

2020-11-30 09:16 UTC, viktor-beet-root commented on students/SemenKluchko/hw10-position/style.css
> +    font-family: "Raleway Heavy";
это все тот же Raleway только фонт-вейт у него 900

2020-11-30 09:16 UTC, viktor-beet-root commented on students/SemenKluchko/hw10-position/style.css
> +         url('fonts/raleway.regular-webfont.woff') format('woff');
судя по названию не тот шрифт

2020-11-30 09:16 UTC, viktor-beet-root commented on students/SemenKluchko/hw8_boxmodel/index.html
> +        <section class="container_main">
значит не заметил, а теперь вижу
и нужно исправить)

2020-11-30 09:16 UTC, viktor-beet-root commented on students/SemenKluchko/hw8_boxmodel/style.css
> +    font-family: 'Montserrat', sans-serif;
резервные шрифты

2020-12-06 18:39 UTC, closed without merging