HW11 - Grid
viktor-beet-root/beet-root pull request #128
Opened 2020-11-24 15:35 UTC by SemenKluchko

2020-11-24 15:37 UTC, SemenKluchko commented
Последний коммит - это домашка которую я хотел зареквестить)
Остальные добавились потому-что я смержил с главной веткой остальные дз который ты смержил к себе, что бы главная ветка их тоже видела. 
Ну а потому как я создал эту ветку с дз из главной, видимо потянулось и это все.. Не знаю как поправить(

2020-11-24 23:41 UTC, viktor-beet-root requested changes

2020-11-24 23:41 UTC, viktor-beet-root commented on students/SemenKluchko/hw11-fonts/css/style.css
> +    max-width: 1600px;
и тут ну просто болезнь какая)) не задают ширину для бади))

2020-11-24 23:41 UTC, viktor-beet-root commented on students/SemenKluchko/hw11-fonts/css/style.css
> +    font-size: 18px;
а вот как раз шрифты должны были быть у бади

2020-11-24 23:41 UTC, viktor-beet-root commented on students/SemenKluchko/hw8_boxmodel/index.html
> +        <section class="container_main">
одни секшен на 3 заголовка )) явно не та семантика 
вспоминаем что я говорил про секшин и заголовки

2020-11-30 09:22 UTC, viktor-beet-root commented on students/SemenKluchko/hw11-fonts/css/style.css
> +    margin: 130px 100px 130px;
по бокам не может быть у контейнера 100px 
просто auto и будет по центру

2020-11-30 09:22 UTC, viktor-beet-root commented on students/SemenKluchko/hw11-fonts/index.html
> +                </form>
странная форма получилась)

2020-11-30 09:22 UTC, viktor-beet-root commented on students/SemenKluchko/hw11-fonts/index.html
> +            <p>"What a country!" cried he. "Mere cattle stop the trains, and go by in a procession, just as if they were not impeding travel! Parbleu! I should like to know if Mr. Fogg foresaw this m
отформатируй код
каждый вложенный тег имеет 4 пробела отступ

2020-11-30 09:22 UTC, viktor-beet-root commented on students/SemenKluchko/hw8_boxmodel/index.html
> +        <section class="container_main">
не нужно мержить то что я еще не принял, а то я начанию проверять в разных мержах одни и тот же код)

2020-12-06 18:40 UTC, closed without merging