11_homework_Fonts_WillowCrest
viktor-beet-root/beet-root pull request #129
Opened 2020-11-24 15:39 UTC by dmytrocherepakhin

2020-11-24 23:48 UTC, viktor-beet-root requested changes

2020-11-24 23:48 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/11_homework_Fonts_WillowCrest/css/style.css
> +    margin: 0 auto;
если это бем то мажены для блоков нельзя указывать

2020-11-24 23:48 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/11_homework_Fonts_WillowCrest/css/style.css
> +    margin: 7px 2px 0;
а ты уверен что этот маржин не падет и не разрушит все
мажины в бем это исключение а не правило
используем пидинги

2020-11-24 23:48 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/11_homework_Fonts_WillowCrest/css/style.css
> +    font-family: Lato, sans-serif;
шрифт задай для блока page мы не будем уж так жестко по бему идти

2020-11-24 23:48 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/11_homework_Fonts_WillowCrest/index.html
> +                    </p>
если это должно была быть буквица то бяда ))
погугли как буквицу сделать на css 
ну и на будущее когда начинаешь верстать что-то чего раньше не делал всегда спрашивай гугла))

2020-11-24 23:48 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/11_homework_Fonts_WillowCrest/index.html
> +                    <span class="willow-article__text-quotation_big">“</span>     The engineer did not try to overcome the obstacle, and he was wise.
эта кавычка должна была быть добавлена через псеводо класс

2020-11-25 12:58 UTC, viktor-beet-root requested changes

2020-11-25 12:58 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/11_homework_Fonts_WillowCrest/css/style.css
> +    margin: 0;
это блок и у него маржин 
его тут не должно быть

2020-11-25 13:19 UTC, dmytrocherepakhin commented on students/cherepakhin_dmytro/11_homework_Fonts_WillowCrest/css/style.css
> +    margin: 0;
я думал, что обнулять допускается.

2020-11-25 13:40 UTC, merged