fixing_uppercase_in_forecast
viktor-beet-root/beet-root pull request #130
Opened 2020-11-24 19:50 UTC by dmytrocherepakhin

В прошлый раз изменения не прошли из-за "ignorecase = true" в файле config. Поменял на -false. Работает.

2020-11-24 23:50 UTC, viktor-beet-root requested changes

2020-11-24 23:50 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/8_homework_CSS_BoxModel_Forecast/css/style.css
> +div{
что вот так прям все дивы и застилил

2020-11-24 23:50 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/8_homework_CSS_BoxModel_Forecast/css/style.css
> +transition: all .3s ease-in;
отформатируй код

2020-11-25 00:09 UTC, dmytrocherepakhin commented on students/cherepakhin_dmytro/8_homework_CSS_BoxModel_Forecast/css/style.css
> +div{
просто он одинокий был)

2020-11-25 00:23 UTC, viktor-beet-root requested changes

2020-11-25 00:23 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/8_homework_CSS_BoxModel_Forecast/css/style.css
> +div{
не важно нужно верстать так чтобы потом этот код можно было скопировать на любой сайт и он там ничего не сломал этот сломает

2020-11-25 01:46 UTC, dmytrocherepakhin commented
думал, что исправил, оказалось - как обычно в другой ветке(

2020-11-25 12:53 UTC, merged