Dz7 boxmodel DakinV
viktor-beet-root/beet-root pull request #133
Opened 2020-11-24 22:48 UTC by VitaliyDaykin

2020-11-25 00:19 UTC, viktor-beet-root requested changes

2020-11-25 00:19 UTC, viktor-beet-root commented on students/daikinvitaliy/dz7_boxmodel/index.html
> +	<section class="shell">
неправильно отформатирован код используется табляция, а нужно 4 пробела

2020-11-25 00:19 UTC, viktor-beet-root commented on students/daikinvitaliy/dz7_boxmodel/css/style.css
> +	padding: 133px 170px 100px;
если это была идея поставить блок по центру то не удачная

2020-11-25 00:19 UTC, viktor-beet-root commented on students/daikinvitaliy/dz7_boxmodel/css/style.css
> +	height: 420px;
высоту для ли не задаем

2020-11-25 00:19 UTC, viktor-beet-root commented on students/daikinvitaliy/dz7_boxmodel/css/style1.css
> +	border: none;
это тут явно лишнее

2020-11-25 00:19 UTC, viktor-beet-root commented on students/daikinvitaliy/dz7_boxmodel/index1.html
> +			<h3>CSS Weather Forecast<i class="wi wi-sunrise"></i></h3>
код отформатирован неверно

2020-11-25 00:19 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +					<label></label><option value="more than three">больше трех</option>
что-то ты тут не то сделал

2020-11-25 00:19 UTC, viktor-beet-root commented on students/daikinvitaliy/klasswoork_blok/css/style.css
> +border: 1px solid red
отформатируй код

2020-11-25 10:11 UTC, VitaliyDaykin commented on students/daikinvitaliy/dz7_boxmodel/index1.html
> +			<h3>CSS Weather Forecast<i class="wi wi-sunrise"></i></h3>
сделал настройки , теперь четное количество

2020-11-25 10:12 UTC, VitaliyDaykin commented on students/daikinvitaliy/dz7_boxmodel/index.html
> +	<section class="shell">
сделал настройки , теперь четное количество

2020-11-25 12:55 UTC, viktor-beet-root requested changes

2020-11-25 12:55 UTC, viktor-beet-root commented on students/daikinvitaliy/dz7_boxmodel/css/style.css
> +	font-family: "PT Sans", Arial, Helvetica, sans-serif;
файл отформатирован не верно 
мы используем не табуляцию а 4 пробела
погугли как настроить vs code на 4 пробела

2020-11-25 12:55 UTC, viktor-beet-root commented on students/daikinvitaliy/dz7_boxmodel/index.html
> +	<section class="shell">
тут стоит символ табуляции, а нужны пробелы

2020-12-02 14:54 UTC, viktor-beet-root requested changes

2020-12-02 14:54 UTC, viktor-beet-root commented on students/daikinvitaliy/dz7_boxmodel/css/style.css
> +	font-family: "PT Sans", Arial, Helvetica, sans-serif;
у тебя стоит идин символ табуляции а не 4 пробела

2020-12-05 16:28 UTC, merged