BEM homework by IGOR .G
viktor-beet-root/beet-root pull request #138
Opened 2020-11-25 17:29 UTC by JSpongeBob

2020-11-27 11:42 UTC, viktor-beet-root requested changes

2020-11-27 11:42 UTC, viktor-beet-root commented on students/guntsovIgor/BEM_hw/css/normalize.css
> +html,
а говорил что бем и нормалайз не совместимы))

2020-11-27 11:42 UTC, viktor-beet-root commented on students/guntsovIgor/BEM_hw/css/style.css
> +   background: url('../img/img-2.jpg') no-repeat;
а если фон будет меньше экрана?

2020-11-27 11:42 UTC, viktor-beet-root commented on students/guntsovIgor/BEM_hw/css/style.css
> +    font-family: 'Raleway';
мы решили что для блока пейдж задаем шрифт и все что для него

2020-11-27 11:42 UTC, viktor-beet-root commented on students/guntsovIgor/BEM_hw/index.html
> +                    <a class="logo__link" href="#">Cahee</a>
элемент есть, а блока нет))

2020-11-27 11:42 UTC, viktor-beet-root commented on students/guntsovIgor/BEM_hw/index.html
> +          <section class="main__info">
оба секшина это блок

2020-11-27 21:11 UTC, merged

2020-11-29 11:30 UTC, ID-G9088 commented on students/guntsovIgor/BEM_hw/css/normalize.css
> +html,
так а я его и не подключал)