12_homework FreshLine
viktor-beet-root/beet-root pull request #139
Opened 2020-11-25 20:03 UTC by dmytrocherepakhin

2020-11-27 12:28 UTC, viktor-beet-root requested changes

2020-11-27 12:28 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/css/style.css
> +font-family: Raleway, sans-serif;
отформатируй код
добавь резервных шрифтов

2020-11-27 12:28 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/css/style.css
> +    height: 67px;
не тут можно без высоты

2020-11-27 12:28 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/css/style.css
> +    align-self: flex-end;
блок не может иметь этого
это свойство влияет на внешнее поведение 
это свойство может быть у элемента

2020-11-27 12:28 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/css/style.css
> +    padding-right: 151px;
это явно не то я уже говорил про большие паддинги по бокам, а тут еще и разные

2020-11-27 12:28 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/css/style.css
> +    margin: 18px;
этот маржин вылезет за родителя

2020-11-27 12:28 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/css/style.css
> +    margin: 18px;
я на прошлом занятии про это говорил 
лучше использовать паддинг

2020-11-27 12:28 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/index.html
> +                        <div class="menu__item_rectangle"></div>
а афтер и бефор для чего 
ну нужно добалять пустые теги там где этого можно не делать

2020-11-27 12:28 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/index.html
> +                    <a href="#" class="menu__item_link">
блочные элементы в нутри строчного
тут этого можно было избежать
так не правильно

2020-11-27 12:28 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/index.html
> +                <p class="section-bottom__info_text2">
section-bottom__info_text1 section-bottom__info_text2
это не два элемента а один section-bottom__info_text

2020-11-27 17:31 UTC, dmytrocherepakhin commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/index.html
> +                <p class="section-bottom__info_text2">
лайнхейт между абзацами отличается от межстрочного, поэтому пришлось делать отдельными абзацами.

2020-11-30 08:32 UTC, viktor-beet-root requested changes

2020-11-30 08:32 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/css/style.css
> +    font-family: Raleway, sans-serif;
резервные шрифты?

2020-11-30 08:32 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/index.html
> +                    </div>
меню это традиционно nav>ul>li>a

2020-11-30 08:32 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/index.html
> +    <section class="section-top">
тут должен был быть хедер

2020-11-30 08:32 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/index.html
> +        <div class="section-top_header-center">
этого тут не должно быть

2020-11-30 08:32 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/index.html
> +            <header class="header section-top_header">
внутри хедера нужно создать див с классом контейнер и модификатором центр

2020-11-30 08:32 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/index.html
> +        <div class="section-top__content">
тут должен был начаться секшен

2020-11-30 08:32 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/index.html
> +            <h1 class="section-bottom__info_header">
h1 должен быть только 1 на страницу

2020-11-30 08:32 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_FreshLife/index.html
> +                    <image  x="0px" y="0px" width="24px" height="40px"  xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAoCAQAAABOBPLeAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAAC
это не контентная картинка ее можно добавить через css
это не свг, а png
это должно быть ссылка кликнув на которую страница прыгает на About US

2020-11-30 11:01 UTC, dmytrocherepakhin commented
хедер поднял вверх, но у него с секшином один бэкграунд. Получилось только через абсолют.

2020-12-01 15:40 UTC, merged