12 homework css bem nike
viktor-beet-root/beet-root pull request #142
Opened 2020-11-28 16:43 UTC by dmytrocherepakhin

2020-11-28 19:31 UTC, viktor-beet-root requested changes

2020-11-28 19:31 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +    background-image: url(../img/main_bg.jpg);
фон в данном случае должен быть у бади

2020-11-28 19:31 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +    flex-direction: row;
оно и так ров

2020-11-28 19:31 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +    overflow: hidden;
что-то мне подсказывает что, что-то тут не так)

2020-11-28 19:31 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +    display: none;
я говорил как элементы форм прятать
по тегу в БЕМе нельзя ничего делать

2020-11-28 19:31 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +	padding: 5px 5px;
отформатируй код

2020-11-28 19:31 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +.label_color_light-blue span{
первое по тегу в беме ничего не делаем
второй начиная с 164 ст. у тебя дублируются свойства одни и те же для разных модификатооров
это значит что-то не так нужно чтобы лейблы были элементами блока с форомлением
а модификатор менял только цвет

2020-11-28 21:34 UTC, viktor-beet-root requested changes

2020-11-28 21:34 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +    display: none;
и веже элементы форм через дисплей нан мы не скрываем

2020-11-28 21:34 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +	padding: 5px 5px;
не отформатированно

2020-11-29 00:39 UTC, viktor-beet-root requested changes

2020-11-29 00:39 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +    display: none;
а тут не исправил

2020-11-30 08:24 UTC, viktor-beet-root requested changes

2020-11-30 08:24 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +    clip-path: ellipse(0 0 0 0);
не я тогда не то показал видать
нужно clip: rect(0 0 0 0)

2020-11-30 08:24 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +    clip-path: ellipse(0 0 0 0);
и тут

2020-11-30 08:37 UTC, dmytrocherepakhin commented on students/cherepakhin_dmytro/12_homework_CSS_BEM_Nike/css/style.css
> +    clip-path: ellipse(0 0 0 0);
так лучше, а то раньше одиночные пиксели рядом с формой болтались.

2020-11-30 10:02 UTC, merged