Kirushov Aleksandr Hw textgrid 21 11
viktor-beet-root/beet-root pull request #146
Opened 2020-11-29 23:03 UTC by oleksandrkirushov

2020-11-30 09:36 UTC, viktor-beet-root requested changes

2020-11-30 09:36 UTC, viktor-beet-root commented on students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/css/style.css
> +h1{
не слизируй по тегу это плохо
потом если этот блок нужно будет куда-то вставить начнутся проблемы

2020-11-30 09:36 UTC, viktor-beet-root commented on students/kirushov_aleksandr/18_11homework_positioning/task_1_blog/blog.html
> +                        <br><span class="month">NOV</span>
бр тут лишний

2020-11-30 09:36 UTC, viktor-beet-root commented on students/kirushov_aleksandr/18_11homework_positioning/task_1_blog/blog.html
> +                    <p>Green Smoothies: Too Much of a Good Thing?</p>
а это был заголовок

2020-11-30 09:36 UTC, viktor-beet-root commented on students/kirushov_aleksandr/18_11homework_positioning/task_1_blog/css/style.css
> +    position: absolute;
это не нужно

2020-11-30 09:36 UTC, viktor-beet-root commented on students/kirushov_aleksandr/18_11homework_positioning/task_1_blog/blog.html
> +                    <p>By Auskteez - 2 hours ago</p>
заголовку и тексту под ним нужна обертка, и именно она должно быть абсолют

2020-11-30 09:36 UTC, viktor-beet-root commented on students/kirushov_aleksandr/21_11homework_textgrid/task_1/css/style.css
> +    padding: 110px 30px 110px 0;
какой-то крывой паддинг)

2020-11-30 09:36 UTC, viktor-beet-root commented on students/kirushov_aleksandr/21_11homework_textgrid/task_2/css/style.css
> +    margin-top: 150px;
контейнер не отцентрирован

2020-12-01 20:24 UTC, oleksandrkirushov commented on students/kirushov_aleksandr/18_11homework_positioning/task_1_blog/css/style.css
> +    position: absolute;
Хорошо. Тогда, дата будет тусклой, и я не могу понять как без этого, что б она была четко белой?

2020-12-02 14:42 UTC, viktor-beet-root requested changes

2020-12-02 14:42 UTC, viktor-beet-root commented on students/kirushov_aleksandr/18_11homework_positioning/task_1_blog/css/style.css
> +    position: absolute;
можно z-index родителю дать

2020-12-04 16:57 UTC, viktor-beet-root requested changes

2020-12-04 16:57 UTC, viktor-beet-root commented on students/kirushov_aleksandr/18_11homework_positioning/task_1_blog/css/style.css
> +    position: absolute;
ну и теперь этому спану убери абсолют или посмотри как у меня сделано

2020-12-05 11:54 UTC, viktor-beet-root requested changes

2020-12-05 11:54 UTC, viktor-beet-root commented on students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/css/style.css
> +    padding: 133px 170px 100px;
убери паддинг по бокам максимум 15px

2020-12-05 11:54 UTC, viktor-beet-root commented on students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/css/style.css
> +}
ст 111 подумай как сократить код

2020-12-05 11:54 UTC, viktor-beet-root commented on students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/css/style.css
> +    margin-right: auto;
зачем писать отдельно лево право если есть одно свойство для этого

2020-12-05 11:54 UTC, viktor-beet-root commented on students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/css/style.css
> +    font-family: Montserrat;
не резервных шрифтов

2020-12-05 11:54 UTC, viktor-beet-root commented on students/kirushov_aleksandr/14_11hw_bloxmodel/task_2/box_weather.html
> +                    <span>Lisbon</span><br><span>21&#176;С </span><i class="wi wi-day-sunny"></i>
убери тег br
подумай как сделать так чтобы город занимал всю строку

2020-12-12 10:55 UTC, viktor-beet-root requested changes

2020-12-12 10:55 UTC, viktor-beet-root commented on students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/css/style.css
> +    font-family: Montserrat;
ты уже должен знать что тут не так

2020-12-18 11:29 UTC, viktor-beet-root requested changes
Conflicting files
students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/bloxmodel_1.html
students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/css/style.css
students/kirushov_aleksandr/14_11hw_bloxmodel/task_2/box_weather.html
students/kirushov_aleksandr/14_11hw_bloxmodel/task_2/css/style.css
нужно решить конфликты

2021-03-22 20:01 UTC, closed without merging