Kirushov Aleksandr Hw_bem_23_11
viktor-beet-root/beet-root pull request #159
Opened 2020-12-05 19:48 UTC by oleksandrkirushov

2020-12-06 14:27 UTC, viktor-beet-root requested changes

2020-12-06 14:27 UTC, viktor-beet-root commented on students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/bloxmodel_1.html
> +                            <g>
эти теги `<g>` можно удалять

2020-12-06 14:27 UTC, viktor-beet-root commented on students/kirushov_aleksandr/18_11homework_positioning/task_2/css/style.css
> +    font-size: 16 px;
лишний пробел после 16

2020-12-09 22:49 UTC, oleksandrkirushov commented on students/kirushov_aleksandr/18_11homework_positioning/task_2/css/style.css
> +    font-size: 16 px;
Виктор, нужна помощь) пофиксил эту ветку, но когда запушил ветку, то создался новый пулреквест, а не добавился новый коммит сюда. В чем может быть проблема?

2020-12-12 11:02 UTC, viktor-beet-root requested changes

2020-12-12 11:02 UTC, viktor-beet-root commented on students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/bloxmodel_1.html
> +                            <g>
а они все еще тут

2020-12-12 11:02 UTC, viktor-beet-root commented on students/kirushov_aleksandr/14_11hw_bloxmodel/task_2/box_weather.html
> +                <span>Lisbon</span><br><span>21&#176;С </span><i class="wi wi-day-sunny"></i>
сделай все тоже только без тега БР

2020-12-12 11:02 UTC, viktor-beet-root commented on students/kirushov_aleksandr/18_11homework_positioning/task_1_blog/blog.html
> +                        <br><span class="month">NOV</span>
не используй те БР

2020-12-12 11:02 UTC, viktor-beet-root commented on students/kirushov_aleksandr/18_11homework_positioning/task_1_blog/css/style.css
> +    background: linear-gradient(0deg, rgba(2,0,36,1) 0%, rgba(0,0,0,1) 100%, rgba(0,212,255,1) 100%);
там градиент должен быть от черного полупрозрачного к черному прозрачному, а тут еще и два значения на 100%

2020-12-12 11:02 UTC, viktor-beet-root commented on students/kirushov_aleksandr/18_11homework_positioning/task_2/css/style.css
> +    font-size: 16 px;
этого значит фиксил в другой ветке

2020-12-18 11:31 UTC, viktor-beet-root requested changes
Conflicting files
students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/bloxmodel_1.html
students/kirushov_aleksandr/14_11hw_bloxmodel/task_1/css/style.css
students/kirushov_aleksandr/14_11hw_bloxmodel/task_2/box_weather.html
students/kirushov_aleksandr/14_11hw_bloxmodel/task_2/css/style.css
students/kirushov_aleksandr/16_11homework_flexbox/task_1_coffee/coffee.html
students/kirushov_aleksandr/16_11homework_flexbox/task_1_coffee/css/style.css
students/kirushov_aleksandr/index.html

2021-03-22 20:01 UTC, closed without merging