Js hw02 19 12 Kirushov Aleksandr
viktor-beet-root/beet-root pull request #179
Opened 2020-12-20 00:01 UTC by oleksandrkirushov

2020-12-22 21:44 UTC, viktor-beet-root requested changes

2020-12-22 21:44 UTC, viktor-beet-root commented on students/kirushov_aleksandr/js_hw02_19_12/js/script.js
> +    }
ну как бы это читать глаза можно вынуть
попробуй выравнять конструкция с помощью else if

2020-12-22 21:44 UTC, viktor-beet-root commented on students/kirushov_aleksandr/js_hw02_19_12/js/script.js
> +let year = prompt("Укажите год", "");
это конст

2020-12-22 21:44 UTC, viktor-beet-root commented on students/kirushov_aleksandr/js_hw02_19_12/js/script.js
> +if (year % 400 == 0 || (year % 4 == 0 && year % 100 !== 0)) {
скобки раставлены не верно год кратен (400 или 4) и (не кратен 100)

2020-12-22 21:44 UTC, viktor-beet-root commented on students/kirushov_aleksandr/js_hw02_19_12/js/script.js
> +}
тут больше вич просится или елсе иф

2020-12-22 21:44 UTC, viktor-beet-root commented on students/kirushov_aleksandr/js_hw02_19_12/js/script.js
> +}
выравнять тут вложенные ифы не нужны есть или свич или елсе иф

2020-12-22 21:44 UTC, viktor-beet-root commented on students/kirushov_aleksandr/js_hw02_19_12/js/script.js
> +    bal = bal + 0;
а какой тут скрытый смысл))

2020-12-22 21:44 UTC, viktor-beet-root commented on students/kirushov_aleksandr/js_hw02_19_12/js/script.js
> +    console.log(date = 1 + "." + (month + 1) + "." + year10);
консоли не каких операций

2020-12-22 21:44 UTC, viktor-beet-root commented on students/kirushov_aleksandr/js_hw02_19_12/js/script.js
> +if ((day + 1 == 32 && month < 12) || ((day + 1 == 30 && month == 2) && (year10 % 400 == 0 || (year10 % 4 == 0 && year10 % 100 !== 0))) || ((day + 1 == 29 && month == 2) && (year10 % 400 !== 0 || (yea
ты можешь эту строку прочитать
попробуй сделать последовательные проверки елс иф тут рулит

2020-12-25 14:29 UTC, oleksandrkirushov commented on students/kirushov_aleksandr/js_hw02_19_12/js/script.js
> +if (year % 400 == 0 || (year % 4 == 0 && year % 100 !== 0)) {
тогда будет противоречие, поскольку год не может быть одновременно кратным 400 и не кратным 100

2020-12-26 11:50 UTC, viktor-beet-root requested changes
students/kirushov_aleksandr/index.html
конфликт нужно решить

2021-01-08 17:43 UTC, merged