HW Js 2 Kozachenko
viktor-beet-root/beet-root pull request #194
Opened 2020-12-25 17:59 UTC by dev-Kozachenko

2020-12-28 15:14 UTC, viktor-beet-root requested changes

2020-12-28 15:14 UTC, viktor-beet-root commented on students/oleksandrKozachenko/homework_js/js_2/hw-js_2.html
> +        };
внимательней прочитай задачу
не все кейсы покрыты

2020-12-28 15:14 UTC, viktor-beet-root commented on students/oleksandrKozachenko/homework_js/js_2/hw-js_2.html
> +</html>
про что-то забыл)

2020-12-30 21:07 UTC, dev-Kozachenko commented on students/oleksandrKozachenko/homework_js/js_2/hw-js_2.html
> +        };
Там по кейсам немного не понятно "ребенок (0–2), подросток (12–18)...". Интуитивно хочется исправить ребенок (0–12), а то возраст в диапазоне от 2 до 12 не покрыт

2021-01-15 22:17 UTC, merged