JS Eugene Hryb. Function
viktor-beet-root/beet-root pull request #204
Opened 2021-01-01 20:57 UTC by EugeneHryb

2021-01-08 22:30 UTC, viktor-beet-root requested changes

2021-01-08 22:30 UTC, viktor-beet-root commented on students/EugeneHryb/26_12_HomeWork_JS_Lesson_3/js/script.js
> +        return 1
в данном случае функция не должна ничего возвращать, это просто функция с побочным действием и все.

2021-01-08 22:30 UTC, viktor-beet-root commented on students/EugeneHryb/26_12_HomeWork_JS_Lesson_3/js/script.js
> +    while(confirm('Выпольнить част 1')){
не так жестко не нужно потом задолбемся проверять

2021-01-08 22:30 UTC, viktor-beet-root commented on students/EugeneHryb/26_12_HomeWork_JS_Lesson_3/js/script.js
> +    function areaOfRectangle(number1, number2 = 0){
вот тут-то значение по умолчанию как раз и не нужно, андефайнд это тоже фолс

2021-01-11 20:17 UTC, EugeneHryb commented on students/EugeneHryb/26_12_HomeWork_JS_Lesson_3/js/script.js
> +    while(confirm('Выпольнить част 1')){
Не так жестко, это по вызову функций в цыкле ?

2021-01-15 22:14 UTC, viktor-beet-root requested changes

2021-01-15 22:14 UTC, viktor-beet-root commented on students/EugeneHryb/26_12_HomeWork_JS_Lesson_3/js/script.js
> +    while(confirm('Выпольнить част 1')){
да не нужно это в цикл запихивать просто последовательное выполнение без вопросов

2021-01-16 11:31 UTC, merged