homework4VDaykin
viktor-beet-root/beet-root pull request #211
Opened 2021-01-10 20:54 UTC by VitaliyDaykin

2021-01-16 10:41 UTC, viktor-beet-root requested changes

2021-01-16 10:41 UTC, viktor-beet-root commented on students/daikinvitaliy/JS/dz_js4/js/script.js
> +        if (arguments.length === 1) {
правильней проверять второй аргумент на андефаинд

2021-01-16 10:41 UTC, viktor-beet-root commented on students/daikinvitaliy/JS/dz_js4/js/script.js
> +    if (test4 === false) {
в данном случае сравнение излишне в переменной уже лежит логическое значение

2021-01-16 10:41 UTC, viktor-beet-root commented on students/daikinvitaliy/JS/dz_js4/js/script.js
> +            if (result === true) {
сравнение не нужно

2021-01-16 10:41 UTC, viktor-beet-root commented on students/daikinvitaliy/JS/dz_js4/js/script.js
> +            console.log("не верно введены часы");
если данные пришли не валидные то нужно прекратить дальше работать, а у тебя код выполнится до конца

2021-01-16 10:41 UTC, viktor-beet-root commented on students/daikinvitaliy/JS/dz_js4/js/script.js
> +        let hoursStr = hours.toString(10);
систему исчисления тут не нужно указывать, да и к  строке тут приводить не обязательно, если цифру  конкатенировать со строкой будет строка

2021-01-16 10:41 UTC, viktor-beet-root commented on students/daikinvitaliy/JS/dz_js4/js/script.js
> +        let secondsComparison = Math.abs(taim1 - taim2);
константа

2021-01-16 11:38 UTC, VitaliyDaykin commented on students/daikinvitaliy/JS/dz_js4/js/script.js
> +            console.log("не верно введены часы");
сделал согласно условию. Написать функцию, которая принимает время (часы, минуты, секунды) и выводит его на экран в формате «чч:мм:сс».Если при вызове функции минуты и/или секунды не были переданы, то выводить их как 00. часы: 00: секунды. Я понял так. написали их

2021-01-18 14:37 UTC, viktor-beet-root requested changes

2021-01-18 14:37 UTC, viktor-beet-root commented on students/daikinvitaliy/JS/dz_js4/js/script.js
> +            console.log("не верно введены часы");
а я и не об этом если входные данные неверны то сказать об этом нужно сразу, а не выполнять весь код и ток в конце говорить что что-то пошло нетак

2021-01-19 11:43 UTC, merged