Home work CV git
viktor-beet-root/beet-root pull request #26
Opened 2020-11-04 16:53 UTC by SerhijZhenzhera

2020-11-04 21:01 UTC, viktor-beet-root requested changes

2020-11-04 21:01 UTC, viktor-beet-root commented on students/zhenzhera-serhij/home_work_3_git/CV.txt
> +Rersonal information: Serhij Zhenzhera, 16.VIII.1979, Kyiv, Ukraine, orthodox, shvjed@ukr.net, shvjed1@gmail.com
это похоже что реальный адрес и email если да лучше изменить на вымышленный

2020-11-06 14:44 UTC, SerhijZhenzhera commented on students/zhenzhera-serhij/home_work_3_git/CV.txt
> +Rersonal information: Serhij Zhenzhera, 16.VIII.1979, Kyiv, Ukraine, orthodox, shvjed@ukr.net, shvjed1@gmail.com
нашёл сообщение :-) поменял - надеюсь, закоммитил

2020-11-07 09:50 UTC, viktor-beet-root requested changes

2020-11-07 09:50 UTC, viktor-beet-root commented on students/zhenzhera_serhij/home_work_4_photoshop_2/iconfinder_social_google_plus_710300.svg
> +</style><g id="Layer_3"/><g id="Layer_1"><path d="M69.8,31.6v8h-2.7v-8h-8v-2.6h8v-8h2.7v8h8v2.6H69.8z M49.5,24.7c3.1,1.8,4.7,5.4,4.7,9.3c0,3.7-2,6.6-4.9,8.8   c-2.8,2.2-3.3,3.1-3.3,5c0,1.6,3.3,3.9,4.
в этом и других файлах нет пустой строки в конце файла
перепроверь все

2020-11-08 23:19 UTC, merged