Photoshop
viktor-beet-root/beet-root pull request #29
Opened 2020-11-05 18:10 UTC by Olexandra1502

2020-11-07 09:53 UTC, viktor-beet-root requested changes

2020-11-07 09:53 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_2/.linkproekt.html
> +"пустий рядок)))"
если это пустая строка, то она должна быть пустой))

2020-11-07 10:23 UTC, viktor-beet-root requested changes
и это не та ветка) 
ты из своей создаешь ветку для работы
делаешь задание 
мержишь локально в свою
пушишь свою ветку в свой удаленный репозиторий
открываешь мерж своей главной ветки в мастер

2020-11-07 10:23 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_2/.linkproekt.html
> +"пустий рядок)))"
Я ставлю пустий рядок, а github його забирає

2020-11-07 10:26 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_2/.linkproekt.html
> +"пустий рядок)))"
гит ничего с файлом не делает это делает другой))
ты наверно в VS Code правишь этот файл если да
то кидай вопрос в общий чат или спроси у гугла как настроить VS Code

2020-11-07 10:29 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_2/.linkproekt.html
> +"пустий рядок)))"
В notepad ++ делала

2020-11-08 23:18 UTC, viktor-beet-root requested changes

2020-11-08 23:18 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_2/.linkproekt.html
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
док тайп не тот)
имя файла начинается на точку 
изменить

2020-11-08 23:18 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_2/.linkproekt.html
> +Перелянь документ буде цікаво
этой надписи тут не должно быть

2020-11-09 08:26 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_2/.linkproekt.html
> +Перелянь документ буде цікаво
Забрала

2020-11-09 08:27 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_2/.linkproekt.html
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
Переделала

2020-11-10 11:33 UTC, closed without merging