homework
viktor-beet-root/beet-root pull request #32
Opened 2020-11-06 14:20 UTC by vitaliiosadets

2020-11-06 15:33 UTC, viktor-beet-root requested changes

2020-11-06 15:33 UTC, viktor-beet-root commented on students/osadets_vitalii/photoshophomework/photoshopclasswork/Camera.svg
> +    <filter id="filter" x="665.688" y="964" width="101.312" height="127" filterUnits="userSpaceOnUse">
во всех svg файлах удали атрибут id

2020-11-06 15:33 UTC, viktor-beet-root commented on students/osadets_vitalii/photoshophomework/photoshopclasswork/logo.svg
> +  <image id="logo" width="273" height="273" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAREAAAERCAYAAABclJOOAAAgAElEQVR4nO2dCZQV1bWGf6RBJoVAAEVFBMUoIApPwQlQiUQxoiKSqMEQB5zjhBpQY9AoiXOWA1F
это не векторное изображение

2020-11-06 15:33 UTC, viktor-beet-root commented on students/osadets_vitalii/photoshophomework/photoshopclasswork/specification
> +https://docs.google.com/document/d/1kNr8Yn4o74v7iqzkIcy7ARX7iMezE5mS_MdJhQOsxS4/edit?usp=sharing
пустая строка отсутствует

2020-11-06 15:33 UTC, viktor-beet-root commented on students/osadets_vitalii/photoshophomework/photoshophomeworkpicture/Logo.svg
> +  <image id="Logo" width="112" height="36" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHAAAAAkCAYAAABR/76qAAAJoklEQVRoge1bC7BWVRX+Fh7lKYHiIyHzAWJoBWOKh1JLjQyFbCRTkXDUbCoVegmMkmUWaZohUImD
это не векторное изображение

2020-11-07 10:00 UTC, viktor-beet-root requested changes
и где все шрифты

2020-11-07 10:00 UTC, viktor-beet-root commented on students/osadets_vitalii/photoshophomework/photoshopclasswork/Wg.svg
> +	.st1{font-family:'P22Corinthia';}
а где тогда этот шрифт в шрифтах)

2020-11-07 18:17 UTC, viktor-beet-root requested changes

2020-11-07 18:17 UTC, viktor-beet-root commented on students/osadets_vitalii/5_classwork/book.html
> +</html>
нет пустой строки

2020-11-08 13:12 UTC, vitaliiosadets commented on students/osadets_vitalii/5_classwork/book.html
> +</html>
Это сюда уже классная работа допушилась, а не домашняя фотошоп

2020-11-08 23:01 UTC, merged