5 classwork
viktor-beet-root/beet-root pull request #44
Opened 2020-11-07 15:26 UTC by olhanemensha

2020-11-07 18:23 UTC, viktor-beet-root requested changes

2020-11-07 18:23 UTC, viktor-beet-root commented on students/olha_nemensha/5_classwork/book.html
> +<Footer> By Lev Tolstoy</Footer>
тег не пишется с большой буквы

2020-11-07 18:23 UTC, viktor-beet-root commented on students/olha_nemensha/5_classwork/book.html
> +  <h1>Война и мир. Лев Толстой</h1>
посмотри как другие сделали структуру

2020-11-07 19:53 UTC, viktor-beet-root requested changes

2020-11-07 19:53 UTC, viktor-beet-root commented on students/olha_nemensha/5_classwork/book.html
> +<footer> By Lev Tolstoy</footer>
надпись в тег p

2020-11-07 19:53 UTC, viktor-beet-root commented on students/olha_nemensha/5_classwork/book.html
> +  <h1>Война и мир. Лев Толстой</h1>
структуру нужно все-таки подправить h1 должен иметь свой блок

2020-11-14 19:51 UTC, olhanemensha commented
тут замечания исправила еще в прошлое воскресение

2020-11-14 20:38 UTC, merged