5 classwork
viktor-beet-root/beet-root pull request #45
Opened 2020-11-07 15:26 UTC by Olexandra1502

2020-11-07 18:24 UTC, viktor-beet-root requested changes

2020-11-07 18:24 UTC, viktor-beet-root commented on 5_classwork/glava.html
> +            <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, sequi officiis aut esse velit amet
эти спаны нужно убрать

2020-11-07 18:24 UTC, viktor-beet-root commented on 5_classwork/glava.html
> +</html>
нет последней строки

2020-11-07 18:24 UTC, viktor-beet-root commented on 5_classwork/index.html
> +</html>
строка

2020-11-07 18:24 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_2/.infophotoshop
> +Щоб активувати посилання натисни на нього!
строка

2020-11-08 17:48 UTC, Olexandra1502 commented on 5_classwork/glava.html
> +            <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, sequi officiis aut esse velit amet
забрала

2020-11-08 17:49 UTC, Olexandra1502 commented on 5_classwork/glava.html
> +</html>
я не могу настроить, открываю файл она есть, а тут нету((((

2020-11-08 23:10 UTC, viktor-beet-root requested changes

2020-11-08 23:10 UTC, viktor-beet-root commented on 5_classwork/glava.html
> +        <li><a href="index.html">Назад</a></li>
как-то неожиданно здесь li увидеть этот тег может быть только внутри ul

2020-11-09 08:14 UTC, Olexandra1502 commented on 5_classwork/glava.html
> +        <li><a href="index.html">Назад</a></li>
Забрала

2020-11-09 12:23 UTC, viktor-beet-root requested changes

2020-11-09 12:23 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_2/.infophotoshop
> +Щоб активувати посилання натисни на нього!
не исправленно

2020-11-15 10:36 UTC, closed without merging