5_classwork_daikin
viktor-beet-root/beet-root pull request #54
Opened 2020-11-08 18:04 UTC by VitaliyDaykin

2020-11-08 23:15 UTC, viktor-beet-root requested changes

2020-11-08 23:15 UTC, viktor-beet-root commented on .vscode/settings.json
> +{
нужно убрать этот файл из коммита,
и добавить эту папку в исключения

2020-11-08 23:15 UTC, viktor-beet-root commented on students/daikinvitaliy/5_classwork/index.html
> +<html lang="en">
файл не на английском языке
 проверь все

2020-11-08 23:15 UTC, viktor-beet-root commented on students/daikinvitaliy/5_classwork/index.html
> +
что-то тут пустого пространства много

2020-11-09 12:19 UTC, VitaliyDaykin commented on students/daikinvitaliy/5_classwork/index.html
> +<html lang="en">
ЭТО ИЗ ЗА ПЕРЕВОДЧИКА

2020-11-09 13:03 UTC, viktor-beet-root requested changes

2020-11-09 13:03 UTC, viktor-beet-root commented on students/daikinvitaliy/5_classwork/index.html
> +<html lang="en">
это нужно исправить

2020-11-09 16:10 UTC, merged