Resume web
viktor-beet-root/beet-root pull request #55
Opened 2020-11-08 18:33 UTC by Olexandra1502

2020-11-08 23:22 UTC, viktor-beet-root requested changes

2020-11-08 23:22 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_2/.infophotoshop
> +Щоб активувати посилання натисни на нього!
последняя строка)

2020-11-08 23:22 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_3/.blok1.html
> +<html lang="en">
файл не на английском

2020-11-08 23:22 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_3/.blok1.html
> +.
этой точки тут не должно быть

2020-11-08 23:22 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_3/.blok2.html
> +        <br></br>
тег br не имеет закрывающего <br> можно написать так <br/>

2020-11-08 23:22 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_3/.blok3.html
> +.
уже писал

2020-11-08 23:22 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_3/index.html
> +.
так же

2020-11-08 23:22 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_3/index.html
> +            <li><a href=".blok3.html">Моя робота</li>
файлы не должны начинаться с точки

2020-11-09 08:08 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_3/.blok2.html
> +        <br></br>
Сделала

2020-11-09 08:08 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_3/.blok1.html
> +.
Сделала

2020-11-09 08:08 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_3/.blok1.html
> +<html lang="en">
Изменила

2020-11-09 08:10 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_3/.blok3.html
> +.
Забрала

2020-11-09 08:10 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_3/index.html
> +.
Забрала

2020-11-09 08:10 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_3/index.html
> +            <li><a href=".blok3.html">Моя робота</li>
Забрала

2020-11-09 12:22 UTC, viktor-beet-root requested changes

2020-11-09 12:22 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_2/.infophotoshop
> +Щоб активувати посилання натисни на нього!
все еще не исправлено

2020-11-09 14:31 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_2/.infophotoshop
> +Щоб активувати посилання натисни на нього!
У меня пустая строка там есть, но тут нету и не знаю чего(((

2020-11-09 15:18 UTC, viktor-beet-root requested changes

2020-11-09 15:18 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_2/.infophotoshop
> +Щоб активувати посилання натисни на нього!
может файл не сохранен? нужно найти как добавить

2020-11-09 15:18 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_3/blok2.html
> +        <li><a href="blok3.html">Моя робота</li></a>
тег li может быть только внутри ul
если нужно чтобы в это был список заголовков то нужно в li положить h3 и все li обернуть в ul

2020-11-09 15:18 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_3/blok2.html
> +    <h2>Так, так саме стільки тварин проживає у мене! У мене 6 собак, 2 котів та маленьке кроленя)</h2>
h2 это заголовок этот текст не он,
это абзац
перечитай материалы из https://html5book.ru/osnovy-html/

2020-11-09 15:18 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_3/index.html
> +    <h1> Резюме </h1>
нужно сделать как было показано на занятии section>h1{заголовок}section>h2{позаголовок}p{тут о себе}

2020-11-09 15:22 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_2/.infophotoshop
> +Щоб активувати посилання натисни на нього!
Сохранен(( и сама строка ставится автоматически

2020-11-09 15:28 UTC, viktor-beet-root requested changes

2020-11-09 15:28 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_2/.infophotoshop
> +Щоб активувати посилання натисни на нього!
ее все же нет

2020-11-10 11:33 UTC, closed without merging