5_class_work
viktor-beet-root/beet-root pull request #59
Opened 2020-11-09 11:03 UTC by SerhijZhenzhera

Задание, выполнявшееся на занятии

2020-11-09 12:25 UTC, viktor-beet-root requested changes

2020-11-09 12:25 UTC, viktor-beet-root commented on students/zhenzhera_serhij/5_class_work/5_class_work_text.txt
> +            <div>
если уже есть хедер то див не обязателен в данном случае, дивы нужны как правило для оформления, сейчас это лишнее

2020-11-09 16:12 UTC, viktor-beet-root requested changes

2020-11-09 16:12 UTC, viktor-beet-root commented on students/zhenzhera_serhij/5_home_work/zhenzhera_1.txt
> +        <li><a href="https://www.facebook.com/shvjed" target="blank">Facebook</a>
тут должны были быть иконки социальных сетей

2020-11-09 16:12 UTC, viktor-beet-root commented on students/zhenzhera_serhij/5_home_work/zhenzhera_3.txt
> +        <p>Я отримав виховання, глибоко орієнтоване на пошук нових горизонтів для людства. Коротко кажучи, наше покоління готувалось летіти в Космос, освоювати інші світи. Сучасний поворот науки і те
нет тегов форматирования

2020-11-10 23:37 UTC, SerhijZhenzhera commented on students/zhenzhera_serhij/5_class_work/5_class_work_text.txt
> +            <div>
Убрал. И отступы сделал в 4 пробела, а не 2

2020-11-11 00:48 UTC, SerhijZhenzhera commented on students/zhenzhera_serhij/5_home_work/zhenzhera_3.txt
> +        <p>Я отримав виховання, глибоко орієнтоване на пошук нових горизонтів для людства. Коротко кажучи, наше покоління готувалось летіти в Космос, освоювати інші світи. Сучасний поворот науки і те
(1)убрал <div> из заголовков; (2)закрыл </main>; (3)добавил / в </footer>; (4)увеличил отступы; (5)добавил .svg иконки социальных сетей; (6)добавил тэги логического форматирования <strong> и <em>; (7)добавил H1; (8)закрыл </li>

2020-11-11 00:51 UTC, SerhijZhenzhera commented on students/zhenzhera_serhij/5_home_work/zhenzhera_1.txt
> +        <li><a href="https://www.facebook.com/shvjed" target="blank">Facebook</a>
иконки скачал и добавил; не уверен, что правильно

2020-11-11 10:29 UTC, viktor-beet-root requested changes

2020-11-11 10:29 UTC, viktor-beet-root commented on students/zhenzhera_serhij/5_class_work/5_class_work_text.txt
> +<!DOCTYPE html>
так а почему у файла расширение .txt? это ж HTML

2020-11-11 10:29 UTC, viktor-beet-root commented on students/zhenzhera_serhij/5_class_work/Index.html.txt
> +<!DOCTYPE html>
и тут
проверь все файлы

2020-11-12 10:56 UTC, viktor-beet-root requested changes

2020-11-12 10:56 UTC, viktor-beet-root commented on students/zhenzhera_serhij/6_home_work/6_home_work.txt
> +                <form action="#" method="POST">
в задаче было сделать одну форму, а не много форм

2020-11-12 10:56 UTC, viktor-beet-root commented on students/zhenzhera_serhij/6_home_work/6_home_work.txt
> +                        <p><label for="cs">Кибербезопасность</label><input type="checkbox" id="cs" name="it" value="cs"></p>
только радиобатторы могут иметь одно значение атрибута name чекбоксы нет

2020-11-14 16:42 UTC, viktor-beet-root requested changes

2020-11-14 16:42 UTC, viktor-beet-root commented on students/zhenzhera_serhij/5_class_work/5_class_work_text.txt
> +<!DOCTYPE html>
не исправленно

2020-11-14 16:42 UTC, viktor-beet-root commented on students/zhenzhera_serhij/6_home_work/6_home_work.txt
> +                <form action="#" method="POST">
не исплавленно

2020-11-14 16:42 UTC, viktor-beet-root commented on students/zhenzhera_serhij/7_2a_home_work/7_2_a.html
> +    <div class="left">
не так ненужно 
всегда когда у нас что-то стоит горизонтально значит есть тег обертка 
они все должны иметь родителя
так же поскольку у каждого есть заголовок они могут быть секшинами а не дивами
так же им не нужно давать разные классы так как они однотипны 
тут не блоков, которые отличаются от других

2020-11-14 16:42 UTC, viktor-beet-root commented on students/zhenzhera_serhij/7_2a_home_work/7_2_a.txt
> +<!DOCTYPE html>
и опять txt файл он тут не нужен

2020-11-14 16:42 UTC, viktor-beet-root commented on students/zhenzhera_serhij/Index.html.txt
> +                <li><a href="5_class_work"></a></li>
тут должны быть ссылки на домашние работты

2020-11-27 22:24 UTC, closed without merging