HTMLHomeWork1
viktor-beet-root/beet-root pull request #61
Opened 2020-11-09 13:50 UTC by AndrewKlima

2020-11-09 14:03 UTC, viktor-beet-root requested changes

2020-11-09 14:03 UTC, viktor-beet-root commented on students/andrew_klimenko/HTMLHomeWork1/MyBlogFirstPage.html
> +    <link rel="stylesheet" href="MyBlogFirstPage.css">
не надо так файлы называть старайся не использовать заглавных букв, лучше так my_blog...

2020-11-09 14:03 UTC, viktor-beet-root commented on students/andrew_klimenko/HTMLHomeWork1/MyBlogFirstPage.html
> +</html>
строка

2020-11-09 14:03 UTC, viktor-beet-root commented on students/andrew_klimenko/HTMLHomeWork1/MyBlogHobbies.html
> +</html>
строка

2020-11-09 14:03 UTC, viktor-beet-root commented on students/andrew_klimenko/HTMLHomeWork1/MyBlogHobbies.html
> +</html>
проверь везде

2020-11-09 15:43 UTC, AndrewKlima commented on students/andrew_klimenko/HTMLHomeWork1/MyBlogFirstPage.html
> +</html>
так оно автоматически так делает почем-то, я удаляю ее, нажимю Ctrl+S и оно опять так. сейчас попробую погуглить.

2020-11-14 20:41 UTC, viktor-beet-root requested changes

2020-11-14 20:41 UTC, viktor-beet-root commented on students/andrew_klimenko/HTMLHomeWork1/my-pets.css
> +}
что-то забыл)

2020-11-16 10:27 UTC, merged