Kolya korzh
viktor-beet-root/beet-root pull request #62
Opened 2020-11-09 16:19 UTC by KolyaKorzh

2020-11-09 16:31 UTC, viktor-beet-root requested changes

2020-11-09 16:31 UTC, viktor-beet-root commented on students/kolya_korzh/htmlhomework/page 3.html
> +     </body>
строка
тут и в других

2020-11-09 16:31 UTC, viktor-beet-root commented on students/kolya_korzh/htmlhomework/page 3.html
> +             <img src="Twinpeaks2.jpg" title="twin peaks">
в ul может быть только li

2020-11-09 16:34 UTC, KolyaKorzh commented
после каждого пункта закрывать ul и вставлять картинку?


пн, 9 нояб. 2020 г. в 18:31, Viktor Dehtiarov <notifications@github.com>:

> *@viktor-beet-root* requested changes on this pull request.
> ------------------------------
>
> In students/kolya_korzh/htmlhomework/page 3.html
> <https://github.com/viktor-beet-root/beet-root/pull/62#discussion_r519945799>
> :
>
> > +         <section>
>
> +             <h1> Сериалы</h1>
>
> +         </section>
>
> +        <section>
>
> +         <ul>
>
> +             <li>Twin peaks</li>
>
> +             <img src="Twinpeaks2.jpg" title="twin peaks">
>
> +             <li> Breaking bad</li>
>
> +             <img src="breakingbad.png" title="breaking bad">
>
> +             <li> Ozark</li>
>
> +             <img src="ozark.png" title="ozark">
>
> +             <li> Hannibal</li>
>
> +             <img src="hannibal.png" title = "hannibal"
>
> +         </ul>
>
> +         </section>
>
> +     </body>
>
>
> строка
> тут и в других
> ------------------------------
>
> In students/kolya_korzh/htmlhomework/page 3.html
> <https://github.com/viktor-beet-root/beet-root/pull/62#discussion_r519946440>
> :
>
> > +<!DOCTYPE html>
>
> +<html lang="en">
>
> +     <head>
>
> +      <meta charset="UTF-8">
>
> +      <meta name= "viewport" content="width=device-width, initial-scale=1.0">
>
> +      <title>page2</title>
>
> +      <link rel="stylesheet" href="style.css">
>
> +     </head>
>
> +     <body>
>
> +         <section>
>
> +             <h1> Сериалы</h1>
>
> +         </section>
>
> +        <section>
>
> +         <ul>
>
> +             <li>Twin peaks</li>
>
> +             <img src="Twinpeaks2.jpg" title="twin peaks">
>
>
> в ul может быть только li
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/viktor-beet-root/beet-root/pull/62#pullrequestreview-526432632>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARR3L3UGRO6I6JULBPDVCRLSPAKPLANCNFSM4TPRWZ3A>
> .
>

2020-11-10 09:08 UTC, viktor-beet-root requested changes

2020-11-10 09:08 UTC, viktor-beet-root commented on students/kolya_korzh/htmlhomework/index.html
> +
одна пустая строка должны быть, я говорил лишнего пустого пространства не должно быть

2020-11-10 09:08 UTC, viktor-beet-root commented on students/kolya_korzh/htmlhomework/index.html
> +                 <li><a href="page 3.html" target="_blank" title="cinema">Любимып сериалы</a> </li>
пробел в имени файла, исправить имя и адрес

2020-11-10 09:08 UTC, viktor-beet-root commented on students/kolya_korzh/htmlhomework/index.html
> +             </section>
на уроке как раз говорил про это))

2020-11-10 09:08 UTC, viktor-beet-root commented on students/kolya_korzh/htmlhomework/index.html
> +             </section>
и про это))

2020-11-12 10:50 UTC, viktor-beet-root requested changes

2020-11-12 10:50 UTC, viktor-beet-root commented on students/kolya_korzh/сайтзнакомств/сайтзнакомств.html
> +          background-image: url(mac\ wallpaper\ aesthetic.jpg);
пробелы в пути 
слеши не в ту сторону,
оно у тебя вообще загружается))

2020-11-12 10:50 UTC, viktor-beet-root commented on students/kolya_korzh/сайтзнакомств/сайтзнакомств.html
> +                <p><label>Ваш пол</label></p>
несколько инпутов не могут иметь одни лейбл, у каждого должен быть свой

2020-11-12 10:50 UTC, viktor-beet-root commented on students/kolya_korzh/сайтзнакомств/сайтзнакомств.html
> +                    <option>Мукачево</option>
каждый опшин должен иметь атрибут value со значением на латинице

2020-11-12 10:50 UTC, viktor-beet-root commented on students/kolya_korzh/сайтзнакомств/сайтзнакомств.html
> +                 <p><label>Ваш возраст</label></p>
лейбелы не привязаны к инпутам
проверь все

2020-11-12 10:50 UTC, viktor-beet-root commented on students/kolya_korzh/сайтзнакомств/сайтзнакомств.html
> +                    <option> Сумы</option>
и зачем эти пробелы перед названием города?

2020-12-06 18:38 UTC, closed without merging