HW5 about myselft - Semen Kluchko
viktor-beet-root/beet-root pull request #63
Opened 2020-11-09 16:45 UTC by SemenKluchko

2020-11-10 09:16 UTC, viktor-beet-root requested changes

2020-11-10 09:16 UTC, viktor-beet-root commented on students/SemenKluchko/MainFolder/hobbies.html
> +        <img src="https://www.yamahabicycles.com/globalassets/2020/homepage/homepage-hero/yamaha-power-assist-bicycles-2020-civante-ebike-hero-mobile.jpg" width="350px" alt="this is picture of bicycl
не надо так делать, кросдоменные запросы это не хорошо
скачай положи себе в папку

2020-11-10 09:16 UTC, viktor-beet-root commented on students/SemenKluchko/MainFolder/hobbies.html
> +                <image width="64" height="62" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAA+CAYAAACbQR1vAAAFKUlEQVRogd2be4gXVRTHP/5yKze1tbJd26jWdtXtgSYVSA8lNQmhwCDBIuhB0oM2EOwFFRXYy
это не svg картинки, обычные растровые засунутые в svg файл
найди нормальные svg иконки

2020-11-10 22:24 UTC, SemenKluchko commented on students/SemenKluchko/MainFolder/hobbies.html
> +                <image width="64" height="62" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAA+CAYAAACbQR1vAAAFKUlEQVRogd2be4gXVRTHP/5yKze1tbJd26jWdtXtgSYVSA8lNQmhwCDBIuhB0oM2EOwFFRXYy
тупанул, сори) 
+

2020-11-10 22:24 UTC, SemenKluchko commented on students/SemenKluchko/MainFolder/hobbies.html
> +        <img src="https://www.yamahabicycles.com/globalassets/2020/homepage/homepage-hero/yamaha-power-assist-bicycles-2020-civante-ebike-hero-mobile.jpg" width="350px" alt="this is picture of bicycl
не обратил внимания, изменил 
+

2020-11-11 10:19 UTC, viktor-beet-root requested changes

2020-11-11 10:19 UTC, viktor-beet-root commented on students/SemenKluchko/hw5-about-myself/myCat.html
> +        <img src="https://static01.nyt.com/images/2020/04/22/science/22VIRUS-PETCATS1/22VIRUS-PETCATS1-mediumSquareAt3X.jpg" width="350px" alt="this is picture of Tommy cat" title="Tommy Kluchko" />
не надо создавать кросдоменные запросы сохрани картинку и сделай локальную ссылку
пересмотри все файлы

2020-11-11 10:19 UTC, viktor-beet-root commented on students/SemenKluchko/hw5-about-myself/svg/facebook.svg
> +</g>
говорил что свг нужно чистить тут есть что

2020-11-11 10:19 UTC, viktor-beet-root commented on students/SemenKluchko/hw5-about-myself/svg/github.svg
> +<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><path d="m256 0c-140.609375 0-256 115.390625-256 256 0 119.988281 84.195312 228.984375 196 256v-84.695312c-11.078125 2.425781-21.273438 2
пустая строка
перепроверь все файлы

2020-11-11 17:53 UTC, SemenKluchko commented on students/SemenKluchko/hw5-about-myself/svg/github.svg
> +<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><path d="m256 0c-140.609375 0-256 115.390625-256 256 0 119.988281 84.195312 228.984375 196 256v-84.695312c-11.078125 2.425781-21.273438 2
+

2020-11-11 17:53 UTC, SemenKluchko commented on students/SemenKluchko/hw5-about-myself/svg/facebook.svg
> +</g>
+

2020-11-11 17:53 UTC, SemenKluchko commented on students/SemenKluchko/hw5-about-myself/myCat.html
> +        <img src="https://static01.nyt.com/images/2020/04/22/science/22VIRUS-PETCATS1/22VIRUS-PETCATS1-mediumSquareAt3X.jpg" width="350px" alt="this is picture of Tommy cat" title="Tommy Kluchko" />
+

2020-11-11 17:53 UTC, SemenKluchko commented
Исправил, плюс новую дз, новый реквест не предложило, а залило сюда)

2020-11-12 11:02 UTC, viktor-beet-root requested changes

2020-11-12 11:02 UTC, viktor-beet-root commented on students/SemenKluchko/hw5-about-myself/index.html
> +            <img src="https://i.imgur.com/hYhN87C.jpg" width="350px" alt="this is picture of cutest man in the world" title="Semen Kluchko with his deep grey eyes" />
а это исправить забыл) проверь все файлы

2020-11-14 11:43 UTC, SemenKluchko commented on students/SemenKluchko/hw5-about-myself/index.html
> +            <img src="https://i.imgur.com/hYhN87C.jpg" width="350px" alt="this is picture of cutest man in the world" title="Semen Kluchko with his deep grey eyes" />
я заливал ее в самом начале на файлообменник, по этому думал оставить как есть, так что не забыл)
исправляю

2020-11-14 16:52 UTC, viktor-beet-root requested changes

2020-11-14 16:52 UTC, viktor-beet-root commented on students/SemenKluchko/hw6-forms/index.html
> +                <div><p><label for="name">Name Surname:</label><input type="text" required id="name" placeholder="type here" /></p></div>
где атрибут name
перепроверь все

2020-11-14 16:52 UTC, viktor-beet-root commented on students/SemenKluchko/hw6-forms/index.html
> +                <div><label for="male">Male</label><input type="radio" id="male" name="gender" /></div>
радио обязательно должен иметь валуе

2020-11-14 16:52 UTC, viktor-beet-root commented on students/SemenKluchko/hw6-forms/index.html
> +                <div><label>JavaScrtip<input type="checkbox" name="question" id="js" /></label></div>
чек боксу очень желательно иметь валуе добавь

2020-11-14 16:52 UTC, viktor-beet-root commented on students/SemenKluchko/hw6-forms/index.html
> +                <div><select name="city" id="city" required>
селенкт в див не стоило брать пока)

2020-11-14 16:52 UTC, viktor-beet-root commented on students/SemenKluchko/hw7-css-selectors/style.css
> +    margin: 1%;
мажин лучше не указывать в процентах

2020-11-14 16:52 UTC, viktor-beet-root commented on students/SemenKluchko/hw7-css-selectors/style.css
> +    font-family: "ProximaNova", sans-serif;
этот шрифт нужно подключить его может не быть в системе.

2020-11-14 20:12 UTC, SemenKluchko commented on students/SemenKluchko/hw6-forms/index.html
> +                <div><label>JavaScrtip<input type="checkbox" name="question" id="js" /></label></div>
готово

2020-11-14 20:12 UTC, SemenKluchko commented on students/SemenKluchko/hw6-forms/index.html
> +                <div><label for="male">Male</label><input type="radio" id="male" name="gender" /></div>
готово

2020-11-14 20:12 UTC, SemenKluchko commented on students/SemenKluchko/hw6-forms/index.html
> +                <div><p><label for="name">Name Surname:</label><input type="text" required id="name" placeholder="type here" /></p></div>
готово

2020-11-14 20:12 UTC, SemenKluchko commented on students/SemenKluchko/hw6-forms/index.html
> +                <div><select name="city" id="city" required>
готово

2020-11-14 20:33 UTC, SemenKluchko commented
В формах убрал все <p> , поменял на <strong> где нужно было. 
value добавлены, пересмотрел вроде все ок.
в селекторах добавил фонт локально, подключил
марджин в пикселях исправил

2020-11-14 20:47 UTC, viktor-beet-root requested changes

2020-11-14 20:47 UTC, viktor-beet-root commented on students/SemenKluchko/hw6-forms/index.html
> +                        <label>Python</label><input type="checkbox" value="python" name="question" id="pythn" /></label>
тут и выше ошибка с лейблами не правильно закрыл
если бы проверил валидатором то знал бы об этом зарание

2020-11-15 09:57 UTC, merged