Valeriia bulharu
viktor-beet-root/beet-root pull request #66
Opened 2020-11-10 18:18 UTC by Valeriia-Bulharu

Отправляю долг (домашка на понедельник)

2020-11-10 19:17 UTC, viktor-beet-root requested changes

2020-11-10 19:17 UTC, viktor-beet-root commented on students/valeriia_bulharu/07_Nov_Homework_About_me/Hobbies.html
> +
тут есть лишний пробел и в других файлах

2020-11-10 19:17 UTC, viktor-beet-root commented on students/valeriia_bulharu/07_Nov_Homework_About_me/Hobbies.html
> +                     <p>Sometimes we go to the disco, sometimes organize a picnic in the open air, play sports or watch a nice film. One of my hobbies is cooking. So when my friends come to my house,
этот отступ не нужен h2 и p соседи) одни идут на одном уровне

2020-11-14 09:57 UTC, viktor-beet-root requested changes

2020-11-14 09:57 UTC, viktor-beet-root commented on students/valeriia_bulharu/07_Nov_Homework_About_me/Hobbies.html
> +
все еще не исправлено

2020-11-14 09:57 UTC, viktor-beet-root commented on students/valeriia_bulharu/11_Nov_Homework_Form/form.html
> +           <p>Телефон</p>
у каждого элемента формы должен быть свой лебл

2020-11-14 09:57 UTC, viktor-beet-root commented on students/valeriia_bulharu/11_Nov_Homework_Form/form.html
> +               <option tabindex="24" value="Chernovtsy">Черновцы</option>
tabindex внутри селекта не имеет смысла, это работает только для элементов формы,

2020-11-16 14:14 UTC, Valeriia-Bulharu commented on students/valeriia_bulharu/07_Nov_Homework_About_me/Hobbies.html
> +
fixed

2020-11-16 14:15 UTC, Valeriia-Bulharu commented on students/valeriia_bulharu/11_Nov_Homework_Form/form.html
> +           <p>Телефон</p>
исправлено

2020-11-16 14:15 UTC, Valeriia-Bulharu commented on students/valeriia_bulharu/11_Nov_Homework_Form/form.html
> +               <option tabindex="24" value="Chernovtsy">Черновцы</option>
исправлено

2020-11-18 08:58 UTC, viktor-beet-root requested changes

2020-11-18 08:58 UTC, viktor-beet-root commented on students/valeriia_bulharu/07_Nov_Homework_About_me/Index.html
> +
так и нет пустой строки в конце файла, 
пробел это не пустая строка

2020-11-18 08:58 UTC, viktor-beet-root commented on students/valeriia_bulharu/07_Nov_Homework_About_me/Hobbies.html
> + <br>
на первых уроках я показывал как настроить vs code чтобы он добавлял пустую строку
если тяжело найти в видео, то это может сделать гугл или общий чат))
никаких тегов после  </html> не должно быть только пустая строка

2020-11-18 08:58 UTC, viktor-beet-root commented on students/valeriia_bulharu/07_Nov_Homework_About_me/Hobbies.html
> +                 <li><a href="Index.html">Main Page</a></li>
не нужно использовать заглавные буквы и именах файлов

2020-11-18 08:58 UTC, viktor-beet-root commented on students/valeriia_bulharu/07_Nov_Homework_About_me/Hobbies.html
> +                 <li><a href="Short Story.html">Short Story</a></li>
не нужно использовать пробелы в именах файлов

2020-11-21 22:31 UTC, merged