homework_git_resume
viktor-beet-root/beet-root pull request #7
Opened 2020-11-02 20:55 UTC by Olexandra1502

2020-11-02 20:59 UTC, viktor-beet-root requested changes
тут только пустой файл 
я так понял написание резюме еще впереди

2020-11-02 21:15 UTC, Olexandra1502 commented
а так вірно?

2020-11-03 09:42 UTC, viktor-beet-root requested changes

2020-11-03 09:42 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_1.txt
> +    <p>Вік: 21 рік та 9 місяців</p>
а теперь нужно изменить личный данные причем именно в том коммите в котором они были добавленны))

2020-11-03 09:42 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_1.txt
> +	<p>Мої домашні улюбленці: Кролик Ліза, 5 собак, 3 кота</p>
что-то малова-то для резюме, а прошлый опыт работы

2020-11-03 11:01 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_1.txt
> +	<p>Мої домашні улюбленці: Кролик Ліза, 5 собак, 3 кота</p>
Дороблювати?

2020-11-03 11:02 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_1.txt
> +	<p>Мої домашні улюбленці: Кролик Ліза, 5 собак, 3 кота</p>
Доробити?

2020-11-03 19:31 UTC, viktor-beet-root requested changes

2020-11-03 19:31 UTC, viktor-beet-root commented on students/alexandra_greenberg/d_1.txt
> +	<p>Мої домашні улюбленці: Кролик Ліза, 5 собак, 3 кота</p>
да если маловато, значит доделать, хоть предыдущий опыт работы добавь

2020-11-03 19:33 UTC, Olexandra1502 commented on students/alexandra_greenberg/d_1.txt
> +	<p>Мої домашні улюбленці: Кролик Ліза, 5 собак, 3 кота</p>
Добре, дякую

2020-11-03 21:08 UTC, merged