dz_aboutmeDaikin vitaliy
viktor-beet-root/beet-root pull request #70
Opened 2020-11-10 22:05 UTC by VitaliyDaykin

2020-11-11 10:01 UTC, viktor-beet-root requested changes

2020-11-11 10:01 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_aboutme/hobby.html
> +			<li><a href="o_family.html " target="blank">Seed</a></li>
линий пробел в адресе

2020-11-11 10:01 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_aboutme/hobby.html
> +			<li><a href="o_myself.html" target="blank">About myself</a></li>
значение атрибута таргет не верное

2020-11-11 10:01 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_aboutme/hobby.html
> +				src="imge/youtube_social_media_social_network_logo_logotype_logos_streaming_video_player_red_icon-icons.com_61230 (1) (1).svg"
пробелы в названии картинки нужно переименовать картинку и исправить путь
так же сократить имя

2020-11-11 10:01 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_aboutme/hobby.html
> +		<!--в ряд выстроить можно при помощи css, но мы еще не дошли. Так же можно убрать тег div но тогда потеряеться симантика. Я ТАК ДУМАЮ-->
не нужно оправдываться) я знаю
лишних комментариев не должно быть
допустимо комментарии по теме, чтобы потом вспомнить что делал, но это только на время учебы

2020-11-11 10:01 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_aboutme/o_family.html
> +				>
лишний символ

2020-11-11 12:02 UTC, VitaliyDaykin commented on students/daikinvitaliy/dz_aboutme/hobby.html
> +			<li><a href="o_myself.html" target="blank">About myself</a></li>
не совсем понял? переходит на новую страницу а должен?

2020-11-11 13:02 UTC, viktor-beet-root requested changes

2020-11-11 13:02 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_aboutme/hobby.html
> +			<li><a href="o_myself.html" target="blank">About myself</a></li>
значение атрибута не верное, читай документацию

2020-11-11 22:55 UTC, VitaliyDaykin commented on students/daikinvitaliy/dz_aboutme/hobby.html
> +			<li><a href="o_myself.html" target="blank">About myself</a></li>
я все исправил что не так ?

2020-11-12 11:24 UTC, viktor-beet-root requested changes

2020-11-12 11:24 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +   	</form>
ну вообще-то задача была использовать все элементы формы))

2020-11-12 11:24 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<input type="text" name="username">
нет лейблов

2020-11-12 11:24 UTC, viktor-beet-root commented on students/daikinvitaliy/index.html
> +		<li><a href="5_classwork" target="blank">5_classwork</a></li>
эта ссылка в никуда))

2020-11-12 14:44 UTC, VitaliyDaykin commented on students/daikinvitaliy/index.html
> +		<li><a href="5_classwork" target="blank">5_classwork</a></li>
это я не правильно отправил "о себе"

2020-11-13 09:59 UTC, viktor-beet-root requested changes

2020-11-13 09:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<input type="text" name="surname" placeholder="Фамилия" value="">
нет лейблов

2020-11-13 09:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<p><input type="radio" name="button" value="gg">Женский</p>
нет лейблов 
значение атрибута найм прикольное)) пользуйся гугл транслейтом

2020-11-13 09:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<p><input type="radio" name="button1" value="mm">Нет</p>
выше уже писал найм должен быть информативным

2020-11-13 09:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +			  </select>
нет лейбла

2020-11-13 09:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<input type="file">
нет найма, лейбла

2020-11-13 09:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<input type="checkbox" name="xxx5" value="a5">Всегда опаздываю
нет лейблов

2020-11-13 09:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<button type="reset">Очистить</button>
по всей форме добавить лейблы, с разными способами привязки к инпуту

2020-11-13 09:59 UTC, viktor-beet-root commented on students/daikinvitaliy/index.html
> +		<li><a href="dz_questionnaire" target="_blank">dz_questionnaire</a></li></li>
ссылки не правильные

2020-11-13 09:59 UTC, viktor-beet-root commented on students/daikinvitaliy/index.html
> +	<title>Document</title>
тайтл не правильный

2020-11-13 18:39 UTC, VitaliyDaykin commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<button type="reset">Очистить</button>
тут лейбл как по мне щчас не нужен. можно здесь без него?

2020-11-14 10:59 UTC, viktor-beet-root requested changes

2020-11-14 10:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<input type="text" name="surname" placeholder="Фамилия" id="fdg" value="">
значения атрибутов должны иметь смыл id
если это фамилия то это lastName и т.д.

2020-11-14 10:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<label for="fdg">вписать</label>
лайблы должны иметь смысл)

2020-11-14 10:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<p><input type="radio" name="floor" value="gg">Женский</p>
нет лейблов

2020-11-14 10:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<input type="date" id="date" name="date" value="aa"/>
валуе не нужно для этого типа указывать

2020-11-14 10:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<label><input type="radio" name="sp1" value="mm">Нет</label>
валуе не может быть тут одинаковым

2020-11-14 10:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<p style="text-align: center"><button>Отправить</button>
эта кнопка ничего не отправить 
почитай еще про формы какой тип должен быть у кнопки

2020-11-14 10:59 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +						style="vertical-align: middle">сброс</button></p>
эта кнопка ничего не сбросит

2020-11-15 10:00 UTC, viktor-beet-root requested changes

2020-11-15 10:00 UTC, viktor-beet-root commented on students/daikinvitaliy/dz_questionnaire/anketa.html
> +				<label for="fdg">вписать</label>
не исправлено

2020-11-15 10:33 UTC, merged