Html forms home work
viktor-beet-root/beet-root pull request #71
Opened 2020-11-10 22:07 UTC by AndrewKlima

2020-11-11 10:15 UTC, viktor-beet-root requested changes

2020-11-11 10:15 UTC, viktor-beet-root commented on students/andrew_klimenko/HTMLHomeWork1/MyBlogFirstPage.css
> +body{
не надо использовать в имени файла заглавные буквы
лучше my-blog-first-page.css or my_blog_first_page.css

2020-11-11 10:15 UTC, viktor-beet-root commented on students/andrew_klimenko/HTMLHomeWork1/MyBlogFirstPage.html
> +<!DOCTYPE html>
и тут тоже про имя переименуй все файлы

2020-11-11 10:15 UTC, viktor-beet-root commented on students/andrew_klimenko/HTMLHomeWork1/MyBlogFirstPage.html
> +</html>
нет пустой строки
проверь все файлы

2020-11-11 10:15 UTC, viktor-beet-root commented on students/andrew_klimenko/htmlFormsHomeWork/htmlFormsHomeWork.html
> +                            <label for="userName">Ваше имя <em>*</em></label><input type="text" id="userName" name="userName" required placeholder="Имя..." maxlength="20">
каждый элемент формы должен иметь свою обертку

2020-11-11 10:15 UTC, viktor-beet-root commented on students/andrew_klimenko/htmlFormsHomeWork/htmlFormsHomeWork.html
> +                <form action="#" method="POST" enctype="application/x-www-form-urlencoded">
enctype это лишнее обычно можно не указывать
но есть ситуации когда должно быть, в твоем же случае лишнее

2020-11-11 10:15 UTC, viktor-beet-root commented on students/andrew_klimenko/htmlFormsHomeWork/htmlFormsHomeWork.html
> +                            <label for="playingGames">Играть в настольные игры</label><input type="checkbox" name="playingGames" id="playingGames">
у чекбоксов валуе очень желателен, так как на беке проще обрабатывать

2020-11-11 15:05 UTC, AndrewKlima commented on students/andrew_klimenko/htmlFormsHomeWork/htmlFormsHomeWork.html
> +                            <label for="userName">Ваше имя <em>*</em></label><input type="text" id="userName" name="userName" required placeholder="Имя..." maxlength="20">
в смысле? <legend> должен тоже быть помещен в div?

2020-11-12 11:00 UTC, viktor-beet-root requested changes

2020-11-12 11:00 UTC, viktor-beet-root commented on students/andrew_klimenko/htmlFormsHomeWork/html-forms-home-work.html
> +                            <label for="userName">Ваше имя <em>*</em></label><input type="text" id="userName" name="userName" required placeholder="Имя..." maxlength="20">
каждый лейбел и инпут должны иметь обертку 
я на уроке форму верстал, там все было видно

2020-11-12 11:00 UTC, viktor-beet-root commented on students/andrew_klimenko/htmlFormsHomeWork/htmlFormsHomeWork.html
> +<!DOCTYPE html>
а когда создаешь новый файл старый нужно удалить

2020-11-12 13:39 UTC, AndrewKlima commented on students/andrew_klimenko/htmlFormsHomeWork/htmlFormsHomeWork.html
> +<!DOCTYPE html>
а его удалить надо с локального репозитория? просто если ж я сделаю git reset --hard HEAD~, репозитории не будут совпадать, и оно там что-то выдавать будет.

2020-11-13 09:51 UTC, viktor-beet-root requested changes

2020-11-13 09:51 UTC, viktor-beet-root commented on students/andrew_klimenko/HTMLHomeWork1/MyBlogFirstPage.css
> +body{
не исправленно

2020-11-13 09:51 UTC, viktor-beet-root commented on students/andrew_klimenko/HTMLHomeWork1/MyBlogFirstPage.html
> +</html>
не исправленно

2020-11-13 09:51 UTC, viktor-beet-root commented on students/andrew_klimenko/htmlFormsHomeWork/html-forms-home-work.html
> +<!DOCTYPE html>
не нужно было создавать html-forms-home-work-2fixed.html  для того чтобы исправить работы, исправления вносятся в те же файлы. ну нужно создавать дубли

2020-11-13 09:51 UTC, viktor-beet-root commented on students/andrew_klimenko/htmlFormsHomeWork/htmlFormsHomeWork.html
> +<!DOCTYPE html>
удалить файл - это удалить файл и сделать комит, для этого не нужно его отменять

2020-11-14 20:43 UTC, merged