Kirushov aleksandr 4Homework(Anketa)
viktor-beet-root/beet-root pull request #72
Opened 2020-11-10 22:41 UTC by oleksandrkirushov

2020-11-11 10:27 UTC, viktor-beet-root requested changes

2020-11-11 10:27 UTC, viktor-beet-root commented on students/kirushov_aleksandr/3_homework/hobbies.html
> +            >
такие переносы не тегов не правильные

2020-11-11 10:27 UTC, viktor-beet-root commented on students/kirushov_aleksandr/4_homework/anketa.html
> +                />
форматирование кода должно быть в одном стиле

2020-11-11 10:27 UTC, viktor-beet-root commented on students/kirushov_aleksandr/4_homework/anketa.html
> +                  checked="checked"
это дискриминация)) ты сразу всех мужского пола сделал, а женщины))) не надо выбирать в данных вопросах,
придумай что-то еще где можно использовать чекед

2020-11-11 10:27 UTC, viktor-beet-root commented on students/kirushov_aleksandr/4_homework/anketa.html
> +                <option value="Черновцы">Черновцы</option>
не самое лучшее решение валуе писать на кириллице

2020-11-11 10:27 UTC, viktor-beet-root commented on students/kirushov_aleksandr/4_homework/anketa.html
> +                  <input type="checkbox" value="Компьютерные игры" />Компьютерные игры
тут и выше нет атрибута name он должен быть

2020-11-12 11:22 UTC, viktor-beet-root requested changes

2020-11-12 11:22 UTC, viktor-beet-root commented on students/kirushov_aleksandr/4_homework/anketa.html
> +        <form action="#" method="get">
не тот метод

2020-11-12 11:22 UTC, viktor-beet-root commented on students/kirushov_aleksandr/4_homework/anketa.html
> +                </label>
а эти сироты без обертки остались))
хотя радио кнопки можно и не оборачивать тут уже как по макету будет, но традиционно они располагаются по горизонтали

2020-11-12 11:22 UTC, viktor-beet-root commented on students/kirushov_aleksandr/4_homework/anketa.html
> +            <input type="image" src="images/send2.svg" name="submit" title="Отправить" width="40px" />
не так лучше не делать если нужна картинка в кнопке сабмит, то надо использовать button type submit

2020-11-13 10:07 UTC, viktor-beet-root requested changes

2020-11-13 10:07 UTC, viktor-beet-root commented on students/kirushov_aleksandr/4_homework/anketa.html
> +              Пол:
в данном случае это p

2020-11-14 16:35 UTC, viktor-beet-root requested changes

2020-11-14 16:35 UTC, viktor-beet-root commented on students/kirushov_aleksandr/11_11homework_css/task_1/css/style.css
> +}
это лишнее
ты ниже прописал если наводим на круг то лого меняет цвет

2020-11-14 16:35 UTC, viktor-beet-root commented on students/kirushov_aleksandr/11_11homework_css/task_2/css/style.css
> +    font-family: Trebuchet,  Arial, sans-serif;
шрифт нужно задавать для бади

2020-11-14 16:35 UTC, viktor-beet-root commented on students/kirushov_aleksandr/4_homework/anketa.html
> +              Пол:
тег не закрыт)

2020-11-14 16:35 UTC, viktor-beet-root commented on students/kirushov_aleksandr/4_homework/anketa.html
> +            </p>
не так не правильно, внутри р не может быть дивов

2020-11-16 10:54 UTC, viktor-beet-root requested changes
а зачем ты удалил файл  students/index.html 
востанови)

2020-11-16 11:14 UTC, oleksandrkirushov commented
а зачем, он мне нужен, это был пустой файл, я его в когда-то в начале создал, не знаю зачем

2020-11-16 11:42 UTC, viktor-beet-root requested changes
первое ты его не создавал))
его создал я 
и он нужен)) восстанови

2020-11-16 11:54 UTC, oleksandrkirushov commented
раз так, прошу пардон) сейчс восстновлю

2020-11-16 13:31 UTC, oleksandrkirushov commented
у меня теперь проблема))
я софтом отменил последний коммит восстновил файл и теперь при пуше выдает ошибку

Кристина@DESKTOP-UIDPV11 MINGW64 ~/Desktop/beetacademy/beet-root (kirushov_aleksandr)
$ git push origin kirushov_aleksandr
To https://github.com/oleksandrkirushov/beet-root.git
 ! [rejected]        kirushov_aleksandr -> kirushov_aleksandr (non-fast-forward)
error: failed to push some refs to 'https://github.com/oleksandrkirushov/beet-root.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

2020-11-16 20:12 UTC, merged