osadetsvitalii_6_html_formshomework
viktor-beet-root/beet-root pull request #73
Opened 2020-11-11 13:52 UTC by vitaliiosadets

2020-11-12 10:45 UTC, viktor-beet-root requested changes

2020-11-12 10:45 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework/form.html
> +        <div><p><label for="name">Имя </label><input type="text" id="name" required placeholder="Вася"></p></div>
в данном случае тег абзаца уже не нужен
плашхолдер Вася) явно перебор)

2020-11-12 10:45 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework/form.html
> +        <br>Голубой<input type="checkbox" name="blue" value="blue">
все эти инпуты должны иметь лейблы каждый свой лейбел

2020-11-12 10:45 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework/form.html
> +        </label>
два инпута не могут иметь одни лейбел

2020-11-14 11:30 UTC, vitaliiosadets commented
Исправил

2020-11-14 16:45 UTC, viktor-beet-root requested changes

2020-11-14 16:45 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework/form.html
> +        </label>
не так тоже не надо 
Пол можно взять в р 
а М и Ж в лейблы

2020-11-14 16:45 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework/form.html
> +        <div><label>Любимый цвет(а)</label>
это р

2020-11-14 16:45 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework/form.html
> +         <label><br>Красный <input type="checkbox" name="red" value="red"></label>
бр в таком случе нужно добавить в конце строки после закрывающего лейбл, или же перед открывающим лейблом

2020-11-15 10:05 UTC, viktor-beet-root requested changes

2020-11-15 10:05 UTC, viktor-beet-root commented on students/osadets_vitalii/classwork14/style.css
> +  border: 1px solid black;
ты уже задал линию на 11 строке, но это все равно не правильно так как они будут удваиваться, так как лишки соприкасаются

2020-11-15 10:05 UTC, viktor-beet-root commented on students/osadets_vitalii/classwork1411/index.html
> +<!DOCTYPE html>
а зачем дела копии файлов?

2020-11-15 10:05 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework/form.html
> +        <div><label for="number">Номер телефона</label><input type="number" id="number" required maxlength="14" placeholder="+38000000000"></div>
нет атрибута name перепроверь все инпуты

2020-11-15 10:05 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework6/test.html
> +</html>
нет пустой строки

2020-11-17 19:07 UTC, vitaliiosadets commented
Я исправил Формы.

2020-11-18 09:14 UTC, viktor-beet-root requested changes

2020-11-18 09:14 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework/form.html
> +        <div><label for="number">Номер телефона</label><input type="number" id="number" required maxlength="14" placeholder="+38000000000"></div>
не исправленно

2020-11-18 09:14 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework6/test.html
> +</html>
не исправленно

2020-11-20 12:10 UTC, viktor-beet-root requested changes

2020-11-20 12:10 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework6/test.html
> +</html>
все еще не исправленно

2020-11-20 12:10 UTC, viktor-beet-root commented on students/osadets_vitalii/classwork14/style.css
> +  border: 1px solid black;
не исправленно

2020-11-23 12:57 UTC, vitaliiosadets commented on students/osadets_vitalii/classwork14/style.css
> +  border: 1px solid black;
Я удалил эти файлы, так как сюда допушилась классная работа, поэтому изменить не могу.

2020-11-23 12:59 UTC, vitaliiosadets commented on students/osadets_vitalii/htmlhomework6/test.html
> +</html>
Я удалил эти файлы, так как сюда допушилась классная работа, поэтому изменить не могу.

2020-11-23 13:00 UTC, vitaliiosadets commented
Я удалил эти файлы, так как сюда допушилась классная работа, поэтому изменить не могу.

2020-11-23 16:02 UTC, viktor-beet-root requested changes

2020-11-23 16:02 UTC, viktor-beet-root commented on students/osadets_vitalii/htmlhomework6/test.html
> +</html>
ну они у тебя до сих пор есть во всех мержах)) так что нужно править или закомитить удаление и запушить

2020-11-23 23:53 UTC, viktor-beet-root requested changes

2020-11-23 23:53 UTC, viktor-beet-root commented on students/osadets_vitalii/classwork14/style.css
> +  border: 1px solid black;
эти файлы у тебя в реквесте свисят
ты можешь спулить веку и они у тебя появятся))

2021-02-14 00:54 UTC, merged