homework 6 with forms has been added
viktor-beet-root/beet-root pull request #74
Opened 2020-11-11 16:22 UTC by dmytrocherepakhin

Еще не все формы, буду добивать.

2020-11-12 11:16 UTC, viktor-beet-root requested changes

2020-11-12 11:16 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/forms.html
> +    <title>Document</title>
ну это явно не документ)
измени во всех файлах

2020-11-12 11:16 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/forms.html
> +                </table>
не таблицы можно использовать только для табличных данных

2020-11-12 11:16 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/forms.html
> +                    <tr><td><label for="sex">Sex:</label></td><td>male -<input type="radio" name="sex" id="sex" value="male"> female -<input type="radio" name="sex" value="female"></td></tr>
одни лейбел не может относиться к двум инпутам только к одному

2020-11-12 11:16 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/forms.html
> +                <label for="hobbies"><br> <ins>Hobbies:</ins>
так же у каждого инпута должен быть свой лебел

2020-11-12 11:16 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/forms.html
> +                <p>singing -<input type="checkbox" name="singing"></p>
чекбоксам очень желательно иметь атрибут валуе

2020-11-13 10:04 UTC, viktor-beet-root requested changes

2020-11-13 10:04 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/forms.html
> +                <label for="name">First name: </label><input type="text" name="name" placeholder="insert your name" id="name"><p></p>
зачем тут пустой абзац? 
пустых тегов не должно быть
и так до донца

2020-11-13 10:04 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/forms.html
> +                <label for="name">First name: </label><input type="text" name="name" placeholder="insert your name" id="name"><p></p>
каждая пара лейбл+инпут должны иметь обертку

2020-11-13 10:04 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/forms.html
> +                    <!-- <button type="submit"><img src="submit.svg" alt="submit"></button> -->
просто комментированного кода не должно быть,
допустимы пометки на память))

2020-11-13 10:04 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/index.html
> +        1991-2001   - Military service <p></p>
этот тест должен был быть внутри абзаца, не рядом

2020-11-13 12:53 UTC, viktor-beet-root requested changes

2020-11-13 12:53 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/forms.html
> +                <ins>Sex:</ins><br>
ins тут не причем))
это скорее p
так же нужна обертка для всех сексов))

2020-11-13 19:31 UTC, viktor-beet-root requested changes

2020-11-13 19:31 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/forms.html
> +                <span>Sex:</span>
не все еще не так
этот секс нужно засунуть в див, 
и он не в спане, а в р должнет быть

2020-11-13 19:31 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/6_homework_html_forms/forms.html
> +                        <span><label for="sex_fm">female -</label><input type="radio" name="sex" id="=sex_fm" value="female"></span>
смысла в этом спане нет, если бы ты текст лейбла в спан взял то можно было так оставить)

2020-11-13 19:31 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/index.html
>              <li><a href="git_homework_resume">Git homework - resume</a></li>
если это адрес папки, то он не правильный

2020-11-13 19:39 UTC, dmytrocherepakhin commented on students/cherepakhin_dmytro/index.html
>              <li><a href="git_homework_resume">Git homework - resume</a></li>
это адрес файла из первых занятий, текстовый, без расширения.

2020-11-14 09:50 UTC, viktor-beet-root requested changes

2020-11-14 09:50 UTC, viktor-beet-root commented on students/cherepakhin_dmytro/index.html
>              <li><a href="git_homework_resume">Git homework - resume</a></li>
тогда добавь этому файлу расширение и положи в папку DZ_0

2020-11-14 10:53 UTC, merged