Eugene Hryb HomeWork from 11.11
viktor-beet-root/beet-root pull request #78
Opened 2020-11-13 10:24 UTC by EugeneHryb

Часть 1, задачи без звездочки. Если успею доделать задачи со звездочкой то отправлю отдельным комитом. Но это будет не раньше утра субботы.

2020-11-13 12:48 UTC, viktor-beet-root requested changes

2020-11-13 12:48 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_1/css/style.css
> +@font-face{
шрифт лучше подключать в начале таблицы стилей, так они раньше начнут зугружаться

2020-11-13 12:48 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_1/css/style.css
> +    src: url(../font/ProximaNova-Light.ttf);
тут нужен не лайл, а регуляр

2020-11-13 12:48 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_1/css/style.css
> +    font-family: "ProximaNova_R";
если используется один шрифт с разными начертаниями нужно использовать одно имя

2020-11-13 12:48 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_1/css/style.css
> +    font-weight: normal;
тут нужно указать что это болд

2020-11-13 12:48 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_2/CSS_selector2.html
> +                    <spam>A lot of pickles</spam>
там еще текст в скобках был

2020-11-13 12:48 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_2/CSS_selector2.html
> +                <div class="box">
если все лежит в лейбле то этот див не обязателен, можно сказать что так не правильно, но об этом поговорим в субботу)

2020-11-13 12:48 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_2/css/style.css
> +    position: absolute;
это из разряда, супер костыль)))
есть другие способы растянуть боди на всю высоту)

2020-11-13 12:48 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_2/css/style.css
> +    border-color: #ffffff;
линию правильно указывать одним свойством

2020-11-14 08:09 UTC, EugeneHryb commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_2/css/style.css
> +    position: absolute;
У меня почему-то все равно без костыля не обошлось.

2020-11-14 08:11 UTC, EugeneHryb commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_2/CSS_selector2.html
> +                <div class="box">
Можно я оставлю так )). 
А то когда я пытался убрать div все ламалось. Я конечно на досуге попробую это реализовать.

2020-11-14 17:01 UTC, viktor-beet-root requested changes

2020-11-14 17:01 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_1/css/style.css
> +    font-size: 14px;
это для бади прописываем тут сброс

2020-11-14 17:01 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_1/css/style.css
> +    margin: 1px auto;
1px )) серьезный такой отступ))

2020-11-14 17:01 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_1/css/style.css
> +    margin-left: auto 0px;
с нулем единицы измерения не пишем

2020-11-14 17:01 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_1/css/style.css
> +    font-family: "ProximaNova";
ты уже задал шрифт тут достаточно только жирность задать

2020-11-14 17:01 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_1/css/style.css
> +    border-width: 2px;
для бордера есть одно свойство

2020-11-14 17:01 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_2/CSS_selector2.html
> +                <div class="box">
и все же лейбл это строчный элемент, и див в нем не может быть, нужно переделать)

2020-11-14 17:01 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/CSS selector/Part_2/css/style.css
> +    content: " ( for the next lessons about CSS )";
ну это же перебор,
в афрет и бефор тексты не добавляют,  за редким исключением
в данном случае нужно было добавить только скобки

2020-11-14 17:01 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/familiarity with CSS/01_simple/css/style.css
> +    font-family: Arial, Helvetica, sans-serif;
это для боди

2020-11-14 20:40 UTC, viktor-beet-root requested changes

2020-11-14 20:40 UTC, viktor-beet-root commented on students/EugeneHryb/11_11_HomeWork/familiarity with CSS/02_hard/css/style.css
> +}
а тут не исправил)

2020-11-14 20:45 UTC, EugeneHryb commented on students/EugeneHryb/11_11_HomeWork/familiarity with CSS/02_hard/css/style.css
> +}
Виноват.

2020-11-15 09:56 UTC, merged