Home work  from 14 .11. Блочная модель.
viktor-beet-root/beet-root pull request #88
Opened 2020-11-15 15:39 UTC by EugeneHryb

2020-11-16 10:30 UTC, viktor-beet-root requested changes
weather-icons-master
не нужно было всю папку затягивать в репозиторий
только файл со стилями и шрифт 
остальное нужно удалить

2020-11-16 20:20 UTC, viktor-beet-root requested changes

2020-11-16 20:20 UTC, viktor-beet-root commented on students/EugeneHryb/14_11_HomeWork/namaste_green/namaste_green.html
> +    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
с гугл фонта шрифты нужно все одним махом подключать

2020-11-18 09:44 UTC, EugeneHryb commented on students/EugeneHryb/14_11_HomeWork/namaste_green/namaste_green.html
> +    <link href="https://fonts.googleapis.com/css2?family=PT+Sans&display=swap" rel="stylesheet">
Не знал что так можно было. Спасибо.

2020-11-18 10:23 UTC, viktor-beet-root requested changes

2020-11-18 10:23 UTC, viktor-beet-root commented on students/EugeneHryb/14_11_HomeWork/metcast/css/style.css
> +    font-family: "LucidaSansUnicode";
ты ж для боди уже прописал этот шрифт

2020-11-18 10:23 UTC, viktor-beet-root commented on students/EugeneHryb/14_11_HomeWork/namaste_green/css/style.css
> +    font-family: 'Montserrat', 'PT Sans', sans-serif;
PT Sans не может быть резервным для монтсерата, это второй шрифт,

2020-11-18 10:23 UTC, viktor-beet-root commented on students/EugeneHryb/14_11_HomeWork/namaste_green/css/style.css
> +    fill: white;
филл это свойство свг графики оно должно относиться только к свг, а бокс это класс лишки

2020-11-18 15:15 UTC, EugeneHryb commented on students/EugeneHryb/14_11_HomeWork/metcast/css/style.css
> +    font-family: "LucidaSansUnicode";
Вот здесь мне самому интересно. С боди шрифт не наследуется для этого элемента.

2020-11-18 15:26 UTC, EugeneHryb commented on students/EugeneHryb/14_11_HomeWork/metcast/css/style.css
> +    font-family: "LucidaSansUnicode";
Все, я нашел почему не наследуется и исправил.

2020-11-18 16:49 UTC, merged