HW Box Model - Semen Kluchko
viktor-beet-root/beet-root pull request #94
Opened 2020-11-16 16:56 UTC by SemenKluchko

2020-11-16 19:07 UTC, SemenKluchko commented
буду переделывать...

2020-11-16 20:11 UTC, viktor-beet-root requested changes

2020-11-16 20:11 UTC, viktor-beet-root commented on students/SemenKluchko/hw8_boxmodel/index.html
> +</html>
нет последней строки

2020-11-16 20:11 UTC, viktor-beet-root commented on students/SemenKluchko/hw8_boxmodel/index.html
> +                        <path class="svg_style" fill="#1b1b1b" d="M60 3.976H4v34.011h56zm0-4c2.2 0 4 1.8 4 4v34.011c0 2.2-1.8 4-4 4H34V48h10a2 2 0 0 1 0 4H20a2 2 0 1 1 0-4h10v-6.013H4c-2.2 0-4-1.8-4-
инлайн стилей не должно быть перенеси цвет в css

2020-11-16 20:11 UTC, viktor-beet-root commented on students/SemenKluchko/hw8_boxmodel/style.css
> +font-family: 'PT Sans', sans-serif;
а это уже явно мусор не не напоминалка))

2020-11-16 20:11 UTC, viktor-beet-root commented on students/SemenKluchko/hw8_boxmodel/style.css
> +
не нужно делать этих отступов

2020-11-20 11:45 UTC, viktor-beet-root requested changes

2020-11-20 11:45 UTC, viktor-beet-root commented on students/SemenKluchko/hw8_boxmodel/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=PT+Sans&display=swap" rel="stylesheet">
шрифты нужно подключать до своих стилей

2020-11-20 11:45 UTC, viktor-beet-root commented on students/SemenKluchko/hw8_boxmodel/index.html
> +            <span>who we are</span>
тут все же абзац

2020-11-21 10:20 UTC, merged