flex_hw_1.1 by IGOR G.
viktor-beet-root/beet-root pull request #96
Opened 2020-11-17 18:00 UTC by JSpongeBob

Дз 1.1

2020-11-18 08:54 UTC, viktor-beet-root requested changes
похоже что перфект пикселем ты не проверял))
не похоже что работа сделана по макету

2020-11-18 08:54 UTC, viktor-beet-root commented on students/guntsovIgor/flex/css/style.css
> +    src: url(../fonts/miso-bold.ttf); /* Путь к файлу со шрифтом */
в макете используется два шрифта
одни с двумя вариантами начертаний
это значит должно было быть подключено три файла
ты же тут подключил один и то не правильно)) там тема отрыта по шрифтам

2020-11-18 08:54 UTC, viktor-beet-root commented on students/guntsovIgor/flex/css/style.css
> +  width:360px;
а если экран будет 320 пикселей)

2020-11-20 11:51 UTC, viktor-beet-root requested changes

2020-11-20 11:51 UTC, viktor-beet-root commented on students/guntsovIgor/flex/css/style.css
> +    src: url(../fonts/miso-bold.ttf); /* Путь к файлу со шрифтом */
не исправленно

2020-11-20 11:51 UTC, viktor-beet-root commented on students/guntsovIgor/flex/flex 1.2_hw/css/style.css
> +    src: url(../fonts/HansKendrick.otf); /* Путь к файлу со шрифтом */
я на последнем занятии говорил как должен быть подключен шрифт

2020-11-20 11:51 UTC, viktor-beet-root commented on students/guntsovIgor/flex/flex 1.2_hw/css/style.css
> +} */
эксперименты отставляем себе, сюда только ДЗ
комментарии могут только быть подсказками к коду

2020-11-20 11:51 UTC, viktor-beet-root commented on students/guntsovIgor/flex/flex 1.2_hw/index.html
> +        </div>
я просил чтобы HTML у всех статей был одинаковый

2020-11-20 11:51 UTC, viktor-beet-root commented on students/guntsovIgor/flex/index.html
> +        <img src="img/silver.png" alt="silver"></img>
картинка не имеет закрывающего тега

2020-11-20 21:34 UTC, JSpongeBob commented on students/guntsovIgor/flex/flex 1.2_hw/index.html
> +        </div>
я заливал еще до урока

2020-11-21 10:16 UTC, viktor-beet-root requested changes

2020-11-21 10:16 UTC, viktor-beet-root commented on students/guntsovIgor/flex/css/style.css
> +   @font-face {
отформатируй правильно код

2020-11-21 10:16 UTC, viktor-beet-root commented on students/guntsovIgor/flex/index.html
> +  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet">
шрифт подключаем до своих стилей

2020-11-21 10:16 UTC, viktor-beet-root commented on students/guntsovIgor/flex/flex 1.2_hw/css/style.css
> +  font-family: 'Hanskendrick', Arial, sans-serif;;
две точки с запятой

2020-11-21 10:16 UTC, viktor-beet-root commented on students/guntsovIgor/flex/flex 1.2_hw/css/style.css
> +  padding-right: 240px;
если ты так пытался поставить по центру то это не верно

2020-11-21 10:16 UTC, viktor-beet-root commented on students/guntsovIgor/flex/css/style.css
> +}
контейнер не отцентрирован

2020-11-21 19:16 UTC, viktor-beet-root requested changes

2020-11-21 19:16 UTC, viktor-beet-root commented on students/guntsovIgor/flex/index.html
> +  <meta http-equiv="x-ua-compatible" content="IE=edge">
тут явно перебор 6ст уже добавил ток с буквами играешься
должно быть `<meta http-equiv="X-UA-Compatible" content="ie=edge">`

2020-11-21 22:32 UTC, merged